### ISSUE TITLE
Upside down scan with same score as correct-orientation scan incorrectly has priority

### ISSUE THREAD

**Issue by tiramiseb** [jflesch/paperwork#103]
When two orientations get the same score, the first one OCR'd is chosen by Paperwork.

However, the upside down bmp file is OCR'd first, so if the correct orientation and the upside down incorrect orientation get the same score, the incorrect upside down file is kept by Paperwork.

The regular orientation should be OCR'd first.

**Comment by jflesch** [comment]
Since Tesseract does the orientation detection, this ticket is pretty much obsolete now.
I'm closing it
