### ISSUE TITLE
Export to PDF format: Include the text in the PDF

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#135]
Currently, when we export a document to the PDF format, it only contains the image of the document. Including the text would be nice.

**Comment by jflesch** [comment]
Well, actually, Cairo can do it ... :)
https://github.com/jflesch/paperwork-backend/commit/38632cdb24aee48b8f23531416b27640513c8c5c

**Comment by r0bis** [comment]
Well, this would be a very good feature to include text in any way. In case if one needs to further optimise or edit the PDF one could use MasterPDF Editor for linux. Just getting the text in would be a huge step forward. I am using version 0.3.2 and it only generates pdf images, no "selectable" or searchable text is found.

**Comment by jflesch** [comment]
I understand. What I tried to say in my comment https://github.com/jflesch/paperwork/issues/135#issuecomment-229405178 is that I've added this feature in paperwork-backend. In other words, it will be available in Paperwork 0.4.
(problem is, for now, Paperwork 0.4 is still strongly unstable when scanning ... :/)

**Comment by r0bis** [comment]
That is great, sorry I misunderstood. Fingers crossed that instability in scanning will be resolved. This is a great piece of software. I was just curious about design choice by the way -  I have not seen a way to add document title; effectively all written identification is done through tags and additional text? It is nice to spend absolute minimum time on document processing when scanning. On the other hand document titles /  file names are such time honored tradition... :) I am thinking when number of documents reaches hundreds, names might be handy.
