### ISSUE TITLE
Use GIO (Gnome IO)

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#21]
Using gnome vfs could make things easier on some points: papers could be stored on anything accessible through GIO (samba, ftp, ssh, etc).
Also, it could make the use of the Trash folder easier (see [issue 19](19)]

**Comment by jaesivsm** [comment]
Oh sorry, I thought i search for duplicate better than that. I'm currently looking into how duplicity implemented it.

**Comment by jflesch** [comment]
Actually, if I want to port Paperwork to Android, Gobject in the backend will become a problem.
