### ISSUE TITLE
Label edition dialog : the colorchooser is too complex

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#210]
When editing a label, there are 2 elements: its name and its color. For the color, we currently use the default standard color chooser. Well, it's too complex. We don't need a color chooser with so many way to choose a color. A simple R/G/B chooser would be enough.

**Comment by jflesch** [comment]
Fixed very nicely by Mathieu Jourdan in the unstable branch

**Comment by tYYGH** [comment]
@jflesch rel. use cases: most of my labels are thus coloured: CPAM, Société Générale, Materiel.net, Amazon, Orange, etc. I open the web site, and color-pick the dominant colour of the page.
This allows _very fast_ thumbnails scrolling when you're looking for a particular document!

**Comment by jflesch** [comment]
Hm, good use case. When could help you then is a color picker (see Gimp color selector for instance). [I've added a ticket for 0.4](https://github.com/jflesch/paperwork/issues/404)

**Comment by jflesch** [comment]
Hm actually, I'm wondering if it was not already in 0.2.x. In that case, it would be a regression --> 0.3.0. Let me check
