### ISSUE TITLE
Command line tool

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#214]
A command line tool could be handful for those who want to script things around documents.

**Comment by tiramiseb** [comment]
This would also allow adding a context menu entry in the file browser in order to import PDF documents automatically, without displaying the paperwork interface.

**Comment by tYYGH** [comment]
It is **already** possible to manually create ```$docdir/YYYYMMDD_HHMM_nn_cc/{doc.pdf,paper.?.jpg}```, and even ```echo 'label,rgb(x,y,z)' >$docdir/YYYYMMDD_HHMM_nn_cc/labels```. Such self-created directories are correctly handled when Paperwork is later started.

It could be enough to also be able to optionally replace the ```labels``` file with a ```TODO-LABELS``` file-marker, and optionally add a ```TODO-OCR-{fra,eng,…}``` file-marker in the directory. These markers would get deleted after having triggered the corresponding actions.

However, for the sake of avoiding concurrency problems if Paperwork is running, it may be best to have a different naming scheme for those directories, such as ```YYYYMMDD_HHMM_nnnn.import```, and have Paperwork take each such directory into account as soon as a ```READY``` marker-file is stored inside, and rename the directory to the normal scheme as it is correctly merged into the "database".

This scheme would have one extra advantage over the usual client-server: this would allow adding documents even on computers where Paperwork is not installed. Eg: if the documents are stored on a file server, any device with the right credentials would be able to add documents, even a smartphone, or a remote connection through a VPN…

**Comment by tYYGH** [comment]
In case someone is interested, I wrote a CLI+Web front-end:
http://yalis.fr/cms/index.php/post/2016/01/21/Command-line-and-Web-Interface-for-Paperwork
Cheers,

**Comment by camlafit** [comment]
Hi

Could be a great idea :) I try paperwork and directory structure is not adapted in my use case. Then I scan directly, store document in my logical structure and import from paperwork after.

Could be nice to for example with incron or other system to import in background new file stored.

**Comment by tYYGH** [comment]
Rel. incron, see this:
http://linuxfr.org/news/paperwork-1-0#comment-1681731

**Comment by jflesch** [comment]
I think what we need to do first here is to define the list of commands to add to paperwork-shell.

Right now, I see an option to import a file (something like ```paperwork-shell import [--guess_labels] <file_or_folder>```.

I guess I could also add quite easily:
* ```paperwork-shell search <keyword_1> [<keyword_2>, [<keyword_3>, [...]]]]```
* ```paperwork-shell show <document_id> [<page_nb>]``` (or ```paperwork-shell dump <document_id> [<page_nb>]``` ?)
* ```paperwork-shell delete <document_id>```
* ```paperwork-shell guess_labels <document_id>```
* ```paperwork-shell add_label <document_id> <label>[,#<hex_color>]```
* ```paperwork-shell remove_label <document_id> <label>
* ```paperwork-shell rename <document_id_original> <document_id_new>```
* ```paperwork-shell switch_workdir <new_workdirectory>```
* ```paperwork-shell rescan``` (scan the work directory for changes)

Anything else ?

**Comment by tiramiseb** [comment]
A command to scan a new document ?

**Comment by jflesch** [comment]
Right now, there is already ```paperwork-shell scan```. But it's quite limited (just scan one page, put it in a new document and quit)
So I guess it could be improved too.

**Comment by tYYGH** [comment]
In case that’s any help, when I wrote my own CLI interface, I felt the need for these requests:

```
 Query:
— by date prefix (year, year-month, year-month-day)
— by labels
— by keywords
— case sensitive/insensitive
   Result (WSN):
     OUTPUT   = "[" [ DOC_LIST ] "]" .
     DOC_LIST = DOC { "," DOC } .
     DOC      = "{""folder"":" FOLDER ",""labels"":[" [ LABELS ]
                "],""count"":" COUNT ",""type"":" TYPE ",""etag"":" ETAG "}" .
     FOLDER   = json_string .
     LABELS   = json_string { "," json_string } .
     COUNT    = json_number .
     TYPE     = """pdf""" | """pages""" .
     ETAG     = json_string .

 Retrieve a single document's metadata:
— by ID
   Result (WSN):
     OUTPUT   = DOC .

 Retrieve a document's thumbnails:
— by ID
   Result (WSN):
     OUTPUT   = "[" THUMBS "]" .
     THUMBS   = CONTENTS { "," CONTENTS } .
     CONTENTS = "{""mime"":" MIME ",""data"":" B64_DATA ",""width"":"
                WIDTH ",""height"":" HEIGHT ",""etag"":" ETAG "}" .
     MIME     = json_string .
     B64_DATA = json_string .
     WIDTH    = json_number .
     HEIGHT   = json_number .

 Retrieve a document's page/PDF and metadata:
— by ID and page number
   Result (WSN):
     OUTPUT   = CONTENTS .

 Retrieve a document page's metadata without the actual page:
— by ID and page number
   Result (WSN):
     OUTPUT   = "{""mime"":" MIME ",""width"":" WIDTH ",""height"":"
                HEIGHT ",""etag"":" ETAG "}" .

 Retrieve a raw document's page/PDF without metadata:
— by ID and page number
   Result: page contents.
```

**Comment by jflesch** [comment]
Nice :)

**Comment by camlafit** [comment]
Hi

Looks missing a paperwork-shell import [file/directory]

Km

**Comment by jflesch** [comment]
Also:

```paperwork-shell exportall [folder]```. For those who are bored of Paperwork and just want everything turned into PDF.

**Comment by jflesch** [comment]
search : https://github.com/jflesch/paperwork-backend/commit/a34a0323d8d3b4fffb098b6e8b19a11bec7a9949

**Comment by jflesch** [comment]
dump: https://github.com/jflesch/paperwork-backend/commit/54eff593f828ce9b0d92dbbd8684afb94557f25f

**Comment by jflesch** [comment]
switch_workdir: https://github.com/jflesch/paperwork-backend/commit/3f3d7230becc3d6beb49f5d245dd4950c572ac65

**Comment by jflesch** [comment]
rescan: https://github.com/jflesch/paperwork-backend/commit/45b09d406faff9e0753919b01fa358acb552a896

**Comment by jflesch** [comment]
show: https://github.com/jflesch/paperwork-backend/commit/ec258dbfd2e96144f141e44a400d0f3dff29f98c

**Comment by jflesch** [comment]
import: https://github.com/jflesch/paperwork-backend/commit/f641bb21da688c7b80be91fa93f557bbbf7add8a

**Comment by jflesch** [comment]
delete_doc: https://github.com/jflesch/paperwork-backend/commit/a67b45f3f875b622678758289827bd64a6464fe5

**Comment by jflesch** [comment]
guess_labels: https://github.com/jflesch/paperwork-backend/commit/52f12ab96c45e7449df1a9668fc07a72a7b2f52b

**Comment by jflesch** [comment]
add_label: https://github.com/jflesch/paperwork-backend/commit/e0476818c854e6d9c0d1c9ec56e192b230696d93

**Comment by jflesch** [comment]
remove_label : https://github.com/jflesch/paperwork-backend/commit/e2d4d04ab6029dd25fe0b64b600f4619aa19b1ec

**Comment by jflesch** [comment]
rename: https://github.com/jflesch/paperwork-backend/commit/d248ee032d9d5131db5b035350b1c5bf10a3f713

**Comment by jflesch** [comment]
export_doc: https://github.com/jflesch/paperwork-backend/commit/1a2d4513e695df3c43bea2dbd152866cf8563148

**Comment by jflesch** [comment]
export_all : https://github.com/jflesch/paperwork-backend/commit/12136e2360957e5ee6e2c36d257b6cb461005deb

**Comment by jflesch** [comment]
I think I have implemented all the command listed previously. I'm going to close this ticket. If you see any missing command, please comment and I will reopen this ticket.

**Comment by Ovvovy** [comment]
Hello

While using the import command to import an empty directory paperwork ask for an importer to use but the list is empty so everything throw an error.

I think printing that the directory is empty and exiting paperwork would be better.

Thanks for the great job you are doing

**Comment by jflesch** [comment]
No raising an exception on empty directory can make sense.
And the OCR should be run automatically when the files are imported (if PDF, only if they don't already contain text). If you want to run explicitly the OCR on a document (for instance PDF with crappy text), it will require a new command in paperwork-shell.

But please open new tickets for those feature (import of empty directory + ocr). This ticket was for Paperwork 1.1 and is closed.
