### ISSUE TITLE
Split backend/frontend

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#328]
--> pypaperwork / libpaperwork + paperwork-gui

**Comment by jflesch** [comment]
Quite frankly, the only separation I have is actually the current one:

- Backend : Manage the documents + index
- Frontend : GUI + Scan + OCR

I must only take the time to make 2 separate packages (and probably 2 Git repositories).

**Comment by tYYGH** [comment]
In case someone is interested, I wrote a CLI+Web front-end:
http://yalis.fr/cms/index.php/post/2016/01/21/Command-line-and-Web-Interface-for-Paperwork
Cheers,

**Comment by jflesch** [comment]
Work started:
* Backend : https://github.com/jflesch/paperwork-backend
* Frontend : https://github.com/jflesch/paperwork/tree/unstable

**Comment by jflesch** [comment]
Note that it is already working. There may just be some small things to tune (translations for instance).
So I'm going to close this ticket.
