### ISSUE TITLE
Paperwork crash on import of some PDF files

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#339]
With one particular PDF, the crash is unavoidable. Here is the stderr:
http://yalis.fr/public/www/ppw2.log
It seems to be related to tag auto-detection, because after I restart Paperwork, the document is there, only with no tags.

(Jérôme, je peux envoyer le PDF s’il y a besoin, mais par mail uniquement car il contient des données privées ; si tu es intéressé, envoie un mail à pw_jf@yalis.fr)

For some other PDF (mostly SFR invoices), when the program crashes, if I start Paperwork again, then delete the tag-less document, then quit and restart Paperwork, and finally import the PDF again, _then_ import works, and tags are correctly auto-detected.

**Comment by tYYGH** [comment]
Hi! I’m now running Paperwork 0.2.1. Paper scan is very stable.
But I’m back to running `while true; do paperwork; [ $? -eq 0 ] && break; done` when I import PDF files: *all* my latest PDF invoices make Paperwork crash :-(

Is there something I should try? Some information you need? Here is an example screen-log of the crash&restart (due to the while loop above):
http://yalis.fr/f/h5hki9/

**Comment by jflesch** [comment]
Well, if you want, I guess the stracktrace could be helpful. You will need to apt-get install python-dbg python-poppler-dbg and probably a lot of other debug package :/
Once installed, you can Paperwork in gdb:

$ gdb python
> run /usr/local/bin/paperwork
(import PDF)
> bt
> py-bt

(py-bt may not be available)

**Comment by tYYGH** [comment]
Being out of available PDF files that I usually import, I turned to PDF files from other sources: none made Paperwork crash! So it depends on the PDF creator after all…
Being an Arch linux user, I don’t have `apt-get`, nor do I have the packages you say. Still, I searched the repository and found `python2-gdblib-git`; I installed it but I’m not sure it made any difference.

I finally found a PDF that made the program crash. Here’s the screen-log of the session:
http://yalis.fr/f/wnoesw/
For comparison, here’s now a screen-log for a working session (no crash):
http://yalis.fr/f/zhlvp0/

**Comment by tYYGH** [comment]
Here’s a PDF that makes my paperwork crash: http://yalis.fr/public/www/ko1.pdf
(for some reason, image/pdf/… d’n’d in Write tab never works for me…)

**Comment by jflesch** [comment]
Doesn't crash with the branch 'stable' or 'unstable'.
However, there have been many changes to fix file descriptors leaks with PDF file.
--> can you retry with one of these branches please ?

**Comment by tYYGH** [comment]
Indeed, file “ko1.pdf” now works :-)
There is some improvement: today, only 1 PDF made paperwork crash out of 2 imported. I cannot post this one, but I’ll post a new crashing PDF as soon as I spot a suitable one.

**Comment by tYYGH** [comment]
Here’s the output when the crash occurs:
```
INFO   paperwork.frontend.mainwindow  Import: file:///ici/home/yves/Desktop/FV201500540689.pdf
INFO   paperwork.backend.docimport    Importing doc 'file:///ici/home/yves/Desktop/FV201500540689.pdf' ...
INFO   paperwork.backend.pdf.doc      PDF: Importing 'file:///ici/home/yves/Desktop/FV201500540689.pdf'
INFO   paperwork.frontend.mainwindow  Importing 1 docs and 0 pages
INFO   paperwork.frontend.mainwindow  Showing document 20151113_2000_34
INFO   root                           Showing page 20151113_2000_34 p1
INFO   paperwork.frontend.util.progressivelist List 'pages' : 4 elements displayed (4 additionnal)
/ici/home/yves/.local/bin/paperwork.sh : ligne 5 :  4007 Erreur de segmentation  (core dumped)src/launcher.py
```
Could the fact that my papers are on NFS be related to the issue?

**Comment by jflesch** [comment]
Yes and no.
I fear this may be a race-condition. So using NFS may imply delay making the race-condition happen.

**Comment by jflesch** [comment]
Can you tell me which version of Libpoppler do you use please ?

**Comment by tYYGH** [comment]
```
extra/poppler 0.37.0-1
    PDF rendering library based on xpdf 3.0
extra/poppler-data 0.4.7-1
    Encoding data for the poppler PDF rendering library
extra/poppler-glib 0.37.0-1
    Poppler glib bindings
```

**Comment by jflesch** [comment]
Weird. Even Debian experimental has only Poppler 0.28.1

**Comment by jflesch** [comment]
Ok, I'll test with poppler > 0.37.
Thing is, since I'm too lazy to install Arch, I'll switch to Debian testing. Let's hope it's doesn't break my computer :)

**Comment by jflesch** [comment]
Ok, I'm now using poppler 0.38. I've imported 3 PDF. No crash.

I'll keep using this version of poppler from now on, but I'm going to move this ticket to 0.3.1.

**Comment by jflesch** [comment]
PS: I've only tested with Paperwork testing (future 0.3.0). Since I'm about to release it, I'm not testing anything on 0.2.x anymore.

**Comment by jflesch** [comment]
Do you still have this issue ?

**Comment by tYYGH** [comment]
Hi! You'll be happy to know that the issue is solved.
With branch "stable", I have imported 9 PDF files from 5 different sources, and everything was perfectly stable. Nice :-)

**Comment by jflesch** [comment]
Awesome :)
