### ISSUE TITLE
feature request: possibility to disable automatic tag detection

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#345]
I was rather happy with this feature at first, but it is too buggy. Now I run paperwork like this:
while true; do paperwork; [ $? -eq 0 ] && break; done
Automatic tag detection now kills paperwork for almost each PDF I import; the PDF is correctly imported, but then paperwork dies (hence my supposition that the tags are at fault); upon restart, the document is not there at first, but then it appears (tag-less) at the step “Chargement des vignettes”.

**Comment by tYYGH** [comment]
Hi! Now running paperwork 0.2.1 (still in Arch Linux).

I have doubts about automatic tags being the cause of the crash. I scanned many papers, and had not a single crash, although the guessed tags were wrong more often than right. I’ll just let you decide if the performance issue explained on 2014-11-14 is enough for letting this request opened…

On the other hand, *all* my PDF imports made Paperwork crash; most PDF are of the same sort, however (4 or 5 kinds of invoices). I’ll rather reopen #339 for this.

**Comment by tYYGH** [comment]
Hum… For your information, #339 is not reopened because I don’t seem to have the right to do so. I left a new comment, though.

**Comment by tYYGH** [comment]
I now run the stable branch from git.

I am now sure that the automatic tag detection is not at fault for the crashes. My past months of Paperwork usage result in:
— a 90% crash rate with PDF documents (sadly…),
— a **0%** crash rate with scanned pages!

And, truth be told, the automatic tag detection is awesome!

While an advanced option to disable anything automatic for the benefit of edge cases would be good, I'm not sure about #345 any more. You may close it, or "branch" it, I guess…

**Comment by tYYGH** [comment]
(Sorry, wrong button again. There's some ergonomic issue with these buttons…)

**Comment by jflesch** [comment]
Do you still have this problem with 0.3.0?

**Comment by tYYGH** [comment]
With branch "stable", I saw that tag detection is mostly OK. Missing labels are frequent (this version seems to be more "conservative") but false labels happen much less frequently than before. Anyway, this isn't that much an issue any more, now that labels get updated (along with the date) only once, when the panel is validated.
However, when the panel is validated, the index update (and consequently the refreshing of the document list) seems to be awfully long... But that's a different issue; I close the present one.
