### ISSUE TITLE
Search not displaying all results

### ISSUE THREAD

**Issue by scubbx** [jflesch/paperwork#357]
A Document is loaded from PDF, OCR works and detects words, it is listed in the collection of documents ( (1) and (2) in the following screenshot):
![sshot1](https://cloud.githubusercontent.com/assets/1347421/5555170/f8397d80-8c9e-11e4-8e61-fb5c82d3e33f.png)

A search term is entered into the search-box while the last document of the screenshot above is still selected. This search-term is found in 2 documents (1), but should also be found in the newly created one. Because it still is selected, one can see the boxes that mark a matching search-term in the doucment. Alas, this search term was actually found in this document (2) but it is not displaed in the list of found documents.
![sshot2](https://cloud.githubusercontent.com/assets/1347421/5555171/09b50250-8c9f-11e4-9850-830c071632e3.png)

I already tried restarting Paperwork, rebuilding the Index, optimizing the Index and redoing the OCR on this document.

System: Linux Mint 17.1
Paperworks: 0.2.1, installed with PIP

**Comment by scubbx** [comment]
I just created a PDF which has the same problem and uplaoded it here: http://www.gisforge.com/files/TestDocument.pdf
It is of very low quality, but the words "Übung" and "Abgabe" are still correctly identified by my german OCR. When searching for either of these two words, this document is also not displayed in the list of results.

**Comment by jflesch** [comment]
Ok, I reproduce the problem with your PDF.

**Comment by jflesch** [comment]
Got it:
The problem comes from some obsolete code still looking for .txt files on OCR-ed PDF files. Sorry for that. I'm going to fix it asap.

**Comment by jflesch** [comment]
Fix: 0266e899427766dffe7571d7725c97bed9612ca0

I also found a major issue with image documents + text indexation : 84f9872a62e5f3e9f5ce00a5b03e0cac7cc4ce1f
So I will release a 0.2.2 soon.

**Comment by scubbx** [comment]
It's working now, thank you!
