### ISSUE TITLE
Search not finding first letter in taglist

### ISSUE THREAD

**Issue by scubbx** [jflesch/paperwork#363]
When putting words in the 'Additional keywords' field of the document properties, the first word entered is not considered when searching.
Hereby it does not matter whether the first word is followed by a space or a new line.

**Comment by scubbx** [comment]
I tried it on a different computer with a different collection of documents and the same thing happens.

**Comment by jflesch** [comment]
Fix: acb98e5512cb89fe2ee5f9a1ae9dfd258a767e54 (branch unstable)
I haven't had time to try it yet. If you do, please tell me if it works. Otherwise, I'll test it myself later.

**Comment by scubbx** [comment]
It seems to work now!

**Comment by jflesch** [comment]
Ok. Thanks for reporting this bug and testing the fix.
I'm going to keep the ticket open until I also test it myself.
