### ISSUE TITLE
Errors in composer.phar dependency

### ISSUE THREAD

**Issue by weems** [jflesch/paperwork#365]
Checking composer.json: FAIL
require.jenssegers/agent : unbound version constraints (*) should be avoided
require.erusev/parsedown : unbound version constraints (dev-master) should be avoided
require.thiagoalessio/tesseract_ocr : unbound version constraints (>= 0.2.0) should be avoided
Checking platform settings: OK
Checking git settings: OK

**Comment by jflesch** [comment]
What are you talking about ?

**Comment by weems** [comment]
Apologies, I will remove I meant to add to a different project of the same name.
