### ISSUE TITLE
dépendances sur archlinux

### ISSUE THREAD

**Issue by egide** [jflesch/paperwork#371]
Installation impossible sur ArchLinux :
```
==> Construction et installation du paquet
==> ERREUR : Fonction package() manquante dans /tmp/yaourt-tmp-rc/aur-python2-pyinsane-git/./PKGBUILD
==> ERREUR: Makepkg n'a pas pu construire python2-pyinsane-git.
```
Snif...

**Comment by jflesch** [comment]
1) Please write your bug reports in English.
2) I'm not the one making the AUR package. Please contact the package maintainer.

**Comment by jflesch** [comment]
Also, the package [python2-pyinsane-git](https://aur.archlinux.org/packages/python2-pyinsane-git/) seems quite old. I think you better have a look at the package [python2-pyinsane](https://aur.archlinux.org/packages/python2-pyinsane/).
