### ISSUE TITLE
Documents not displayed

### ISSUE THREAD

**Issue by Che4ter** [jflesch/paperwork#374]
I'v installed paperwork on a fresh ubuntu 15.04 installation and copied my old document archive to the new system. I can run paperwork and i see my documents in the left sidebar, i can even import new ones, but i never see a document in the main screen:( 
Below is the terminal output:
$ paperwork
INFO   paperwork.paperwork            Looking for locales in 'locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/local/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   root                           Will use locales from '/usr/share/locale'
INFO   paperwork.backend.config       Config file found: /home/philipp/.config/paperwork.conf
INFO   paperwork.backend.config       Reloading /home/philipp/.config/paperwork.conf ...
INFO   root                           UI file used: /usr/share/paperwork/mainwindow/appmenu.xml
INFO   root                           UI file used: /usr/share/paperwork/mainwindow/mainwindow.glade

(paperwork:12420): Gtk-WARNING **: Could not load image 'paperwork.svg': Failed to open file '/usr/share/paperwork/mainwindow/paperwork.svg': No such file or directory
INFO   paperwork.frontend.util.actions Action: [Reload current page]
INFO   paperwork.frontend.mainwindow  Showing document 20150503_1749_18
INFO   root                           Showing page Dummy page
INFO   paperwork.frontend.util.progressivelist List 'pages' : 0 elements displayed (0 additionnal)
INFO   root                           Showing page Dummy page
INFO   paperwork.frontend.mainwindow  Image view port resized. (0, 0) --> (1032, 749)
INFO   paperwork.frontend.util.jobs   [Scheduler OCR] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler OCR] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Main] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Main] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Scan] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Scan] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Page boxes loader] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Page boxes loader] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Progress] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Progress] Started
INFO   paperwork.frontend.util.actions Action: [Refresh index]
INFO   paperwork.backend.docsearch    Opening index dir '/home/philipp/.local/share/paperwork/index' ...
INFO   paperwork.backend.docsearch    Opening label_estimators file '/home/philipp/.local/share/paperwork/label_estimators/label_estimators.jbl' ...
INFO   paperwork.frontend.mainwindow  Document examen finished. Updating index ...
INFO   paperwork.frontend.mainwindow  New document: 0
INFO   paperwork.frontend.mainwindow  Updated document: 0
INFO   paperwork.frontend.mainwindow  Deleted document: 0
INFO   paperwork.frontend.mainwindow  No changes
INFO   paperwork.frontend.mainwindow  Searching: []
INFO   paperwork.frontend.util.progressivelist List 'documents' : 11 elements displayed (11 additionnal)
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

INFO   paperwork.frontend.util.actions Action: [Open selected document]
INFO   paperwork.frontend.mainwindow  Showing doc 20150503_1616_35
INFO   paperwork.frontend.mainwindow  Showing document 20150503_1616_35
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/actions.py", line 75, in on_iconview_selection_changed_cb
    return self.__do()
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/actions.py", line 57, in __do
    return self.do(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 1374, in do
    self.__main_win.show_doc(doc)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 3544, in show_doc
    sentence=search)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/pages.py", line 175, in __init__
    self.spinner = SpinnerAnimation((0, 0))
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/animations.py", line 178, in __init__
    self.icon_pixbuf = icon_info.load_icon()
AttributeError: 'NoneType' object has no attribute 'load_icon'
INFO   paperwork.frontend.util.actions Action: [Open selected document]
INFO   paperwork.frontend.mainwindow  Showing doc 20150503_1616_35
INFO   paperwork.frontend.mainwindow  Doc is already shown

![screenshot](https://cloud.githubusercontent.com/assets/4562855/7445683/a6b14248-f1bd-11e4-89ef-69e507a38aff.png)

**Comment by jflesch** [comment]
Looks like a gnome icon (the spinner image) isn't available :/

**Comment by Che4ter** [comment]
you're right, i changed the icon to another and it works again. I'm running gnome 3.14.4 with the default theme so i have no idea why i don't have this icon.

**Comment by jflesch** [comment]
Weird, I'm using Gnome 3.14.1 (Debian) and it works fine.
Anyway, I've commited a fix/workaround :
7c2da159557edfa5878e720d3ebcbe5f8667d1b2

It should be good enough until I figure out what happened.

Thanks for taking the time of reporting this issue.
