### ISSUE TITLE
Feature proposal: Startup parameter for instant document creation

### ISSUE THREAD

**Issue by textPreferred** [jflesch/paperwork#376]
The perfect paperwork workflow would probably consist of the following components:
- a scanner that detects if a new piece of paper has been inserted
- said scanner firing up paperwork
- paperwork starting the scan, creating a new document and doing its magic

While we cannot influence what kind of scanners people use, adding a startup parameter like "--instant-scan" would allow for many possibilities of getting close to the ideal above:
- Adding a short-cut to the desktop or the start menu to immediately start scanning a new document
- Using the scanner's buttons to trigger a paperwork scan (cf. https://wiki.archlinux.org/index.php/Scanner_Button_Daemon)

**Comment by jflesch** [comment]
May be related to #214

**Comment by tYYGH** [comment]
#403 should be solved for this feature to work.

**Comment by jflesch** [comment]
Implemented in paperwork-shell: ```paperwork-shell scan``` will automatically start Paperwork and scan a page in a new document.

https://github.com/jflesch/paperwork-backend/commit/11cbed7b37b4aca713a75fedefb2fc6e3ad27eca
937b9fed4ac3d0d039c66408634957d0e291034e
