### ISSUE TITLE
Config option to disable auto-ANYTHING, please!

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#377]
Paperwork used to be good for me. No more. It’s getting worse by the day (using v0.2.4).
Now, not only do I have to unselect every detected label; I also have to rotate every page!

On the labels side: it has come to the point where almost no label is correct. Often, the autodetected labels are simply those of the previously scanned document (which I had to set myself…). And each change needs its index update :-(

On the orientation side: I _always_ put my papers in the scanner with the right orientation. And the preview while scanning indeed shows the right orientation. But the auto-detection of orientation keeps screwing this, and I have to rotate my pages 90 or 180°. CESU/URSSAF pages, for instance.

So, please, maintain the possibility to do everything by hand, or help me reset/debug/I don’t know/… so that things are bearable again. I’m willing to help; I just don’t know how.

**Comment by jflesch** [comment]
Are you using Tesseract or Cuneiform ? (which one is installed on your computer ?)

**Comment by tYYGH** [comment]
Hi! I’m using Arch Linux, with these installed:
community/tesseract 3.03rc1-3
community/tesseract-data-deu 3.02.02-5
community/tesseract-data-eng 3.02.02-5
community/tesseract-data-fra 3.02.02-5
And Paperwork is set to “French” in the preferences.

**Comment by jflesch** [comment]
And when you run Paperwork from the terminal and you run the OCR on a document, do you see the following message ?

```
INFO   paperwork.frontend.mainwindow.scan Will use tool 'Tesseract'
```

I'm asking because since Tesseract has been used for orientation detection (paperwork 0.2.4), I've had *no* problem with orientation detection *at all*.
And since orientation detection fails, I assume OCR fails as well, which explain why label guessing fails ... :/

Do you have any page/document you could share for testing ? (maybe by blackening the areas that are confidential ?)

**Comment by tYYGH** [comment]
Hi jflesch, thanks for your patience with my bugs :-)
You have probably pinpointed the problem: tesseract failure ⇒ orientation bug ⇒ OCR failure ⇒ labels failure… Indeed, I do have the line you say, but those after are bad:
```
INFO   paperwork.frontend.mainwindow.scan Will use tool 'Tesseract'
INFO   paperwork.frontend.mainwindow.scan Failed to use OCR tool heuristic for orientation detection: 'module' object has no attribute 'can_detect_orientation'
INFO   paperwork.frontend.mainwindow.scan Falling back on Paperwork's heuristic
```

**Comment by jflesch** [comment]
```
INFO   paperwork.frontend.mainwindow.scan Failed to use OCR tool heuristic for orientation detection: 'module' object has no attribute 'can_detect_orientation'
```

You should update Pyocr --> 'sudo pip install --upgrade pyocr' should do the trick.

**Comment by jflesch** [comment]
(weird, setup.py should have done it for you)

**Comment by tYYGH** [comment]
pyocr upgraded from sources to v0.3.0. problem solved!
Thanks
