### ISSUE TITLE
Refresh problem, unusable on restart

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#378]
For completeness, I should mention that first I imported a PDF that made paperwork crash. As I do every time it happens (see #339), I restarted paperwork so that it could recover. And it did.
So I had my PDF imported (but label-less due to the crash), and then I saw that the PDF was bad because it had been created with all pages turned 90°, and you cannot rotate pages that come from a PDF file. So I right-clicked the document in the document list, and deleted the document.

Bug starts here. The document, although deleted, was still displayed in the list. So (usual cure) I stopped paperwork and started it again. Usually, paperwork then recovers (probably removes stale pointers, maybe also detect newly appeared documents such as after an auto-label-crash…). This time, however, it did not.

The console displays:
```
INFO   paperwork.frontend.mainwindow  Searching: []
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paperwork/frontend/mainwindow/__init__.py", line 3187, in on_search_results_cb
    for doc in documents])
  File "/usr/lib/python2.7/site-packages/paperwork/frontend/mainwindow/__init__.py", line 3274, in __get_doc_model_line
    if doc.nb_pages <= 0:
  File "/usr/lib/python2.7/site-packages/paperwork/backend/common/doc.py", line 88, in __get_nb_pages
    self.__cache['nb_pages'] = self._get_nb_pages()
  File "/usr/lib/python2.7/site-packages/paperwork/backend/pdf/doc.py", line 162, in _get_nb_pages
    self._open_pdf()
  File "/usr/lib/python2.7/site-packages/paperwork/backend/pdf/doc.py", line 139, in _open_pdf
    password=None)
GLib.Error: g-file-error-quark: Aucun fichier ou dossier de ce type (4)
```
And the UI’s document list is empty. I’m stuck with an empty paperwork…
Oh, and I forgot: the status bar says “80%”.

**Comment by tYYGH** [comment]
“Reindex all documents” allowed the document list to work again :-) At least, I’ll be able to continue using Paperwork.

**Comment by jflesch** [comment]
I'll try to have a look, but I'm actually making a full rework of the UI for the 0.3.0, so I don't think I'll spend a lot of time on this bug.

**Comment by tYYGH** [comment]
No problem: since the reindex _and_ the newer pyocr, things have been going rather smoothly. Besides, the reindex is a workaround for this bug, so it is not blocking after all!
I’m sure I’ll like 0.3.0 :-)

**Comment by jflesch** [comment]
Did you have this issue again with the branch 'unstable' ?

**Comment by jflesch** [comment]
ping ?

**Comment by tYYGH** [comment]
The circumstances for this bug are a bit peculiar, so I’m not sure. Anyway, the bug did not happen again. I guess we can consider it closed.

**Comment by jflesch** [comment]
Works for me :-)
