### ISSUE TITLE
All document detected as one text area

### ISSUE THREAD

**Issue by programLyrique** [jflesch/paperwork#379]
I have one document when when I put the mouse over the background, every thing on the image becomes white. When I put it over some text which has been detected by the OCR, only the text is highlighted as expected.

If it is a problem related to the OCR (which might be recognizing the background as one big text area...), I think an option to disable OCR per document could be useful.

**Comment by jflesch** [comment]
I'm unsure yet if it's a OCR problem or a highlighting problem.
In any case, highlighting a keyword shouldn't hide any other keyword.

**Comment by jflesch** [comment]
Workaround for 0.4: 1b83e28f57ad5abdd7d58a626d068644ef0f9a24
For 0.5, I'll see for a clean fix.

**Comment by jflesch** [comment]
They appear to come directly from Tesseract.
Tesseract 3.03 returns sometimes word boxes very big and empty (just a space inside).
It's weird, but the workaround implemented here is good enough.
