### ISSUE TITLE
scan preview regression

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#381]
With fresh installs of pyocr 0.3.0 and paperwork 0.2.4, I don’t have a preview anymore while scanning. The scans works, though, as do (now) orientation, OCR, and so on.
Very minor issue. I wonder if it is related to the choice of desktop environment, or chosen theme (rendering glitch), or really a paperwork issue…

**Comment by jflesch** [comment]
Maybe a duplicate of #374 ?

**Comment by jflesch** [comment]
For #374, a workaround has been commited in the stable branch, but not yet released.

**Comment by tYYGH** [comment]
I’ve read #374; not the same. I have the spinner icon (I see it during orientation detection), and I don’t see any alarming message in the terminal, from the time I click the Scan button to the time when paperwork is idle again. Besides, The right side is “blank” (actually a blank A4 page is displayed) only during preview; afterwards, I see the 4 orientation-thumbnails, and then the full scanned page.

**Comment by jflesch** [comment]
My bad, I misread your ticket.

Questions:
- What scanner do you use ?
- Does it work with the program simple-scan ?
- Which GNU/Linux distribution + version do you use ?

**Comment by tYYGH** [comment]
— Epson Perfection 1650 (~ 15yr-old)
— Using either the “epson” driver (seen as “Perfection 1650”), or the “epkowa” driver (seen as “GT-8200” iirc), it works with both xsane and iscan; I had it working with simple-scan some time ago but I removed this software.
— Up-to-date Arch Linux (no version).

**Comment by tYYGH** [comment]
This has been fixed in the 0.2 branch (stable) for at least a couple weeks. Thanks.

**Comment by tYYGH** [comment]
FYI, the problem reappeared for a while, but it disappeared again with the switch to version 0.3. I thus leave this closed.
