### ISSUE TITLE
Detect PDF format with its content (header?) instead of the extension

### ISSUE THREAD

**Issue by tiramiseb** [jflesch/paperwork#385]
I regularely download PDF documents with no extension (named only "Releve" and not "Releve.pdf"). The default viewer (Evince) detects them correctly. Paperwork says it doesn't know how to manage them, so I have to rename them manually.
Paperwork should detect them the same way as Evince does.

**Comment by jflesch** [comment]
https://github.com/ahupp/python-magic

**Comment by jflesch** [comment]
Actually, GLib can take of it, no need for extra dependency.

```py
from gi.repository import Gio
f = Gio.File.new_for_path("./releve-de-compte-decembre-2016.pouet")
i = f.query_info("standard::content-type")
print(i.get_content_type())
```

**Comment by jflesch** [comment]
Done: https://github.com/jflesch/paperwork-backend/commit/3a34b2b9231cf8cb3bafe083c09e362ec87103b6
