### ISSUE TITLE
Use Stroke width transform before Tesseract to improve OCR

### ISSUE THREAD

**Issue by programLyrique** [jflesch/paperwork#386]
Applying Stroke Width transform before Tesseract seems to improve OCR a lot.
See https://github.com/tleyden/open-ocr/wiki/Stroke-Width-Transform

More info on Stroke width transform here: http://libccv.org/doc/doc-swt/
An implementation: https://github.com/tleyden/DetectText

**Comment by jflesch** [comment]
To include in jflesch/pyocr

**Comment by jflesch** [comment]
https://pypi.python.org/pypi/ccv/0.0.5

**Comment by jflesch** [comment]
The parent repository seems more up-to-date : https://github.com/aperrau/DetectText

**Comment by jflesch** [comment]
Implemented : https://github.com/jflesch/libpillowfight

I've implemented other algorithms as well : ACE (Automatic Color Equalization) and Unpaper's algorithms. I'm currently checking [which combination gives the best results](https://github.com/jflesch/paperwork/blob/unstable/scripts/compare_algorithms.py).

**Comment by jflesch** [comment]
I still need to work on it, but preliminary results seem to indicate what I started to guess while implementing SWT : SWT is designed to find text in natural scenes, but not on scanned documents.

On scanned documents, the problem is that the stroke are much smaller than in natural scenes. My implementation is able to locate the text, but not precisely enough --> when it tries to extract the text, it breaks the letters. See for example : [in](https://raw.githubusercontent.com/jflesch/libpillowfight/master/tests/data/black_border_problem.jpg) --> [out](https://raw.githubusercontent.com/jflesch/libpillowfight/master/tests/data/black_border_problem_swt.jpg).

I think I may able to work around it, but I'm wondering if SWT would actually bring any benefit.

**Comment by jflesch** [comment]
My program crashed for some reason after 187 pages (OOM?), but I think it already gives a good enough idea.

```
raw
  maybe:  5451 (  8%) | nb_words: 65372 | perfect: 19882 ( 30%) | garbage:   419 (  0%) | nb_pages:   188 | too_short: 32736 ( 50%) | correctable:  6884 ( 10%) |
unpaper
  maybe:  5450 (  8%) | nb_words: 65197 | perfect: 19680 ( 30%) | garbage:   426 (  0%) | nb_pages:   188 | too_short: 32737 ( 50%) | correctable:  6904 ( 10%) |
swt
  maybe:  5878 (  8%) | nb_words: 65463 | perfect: 18719 ( 28%) | garbage:   478 (  0%) | nb_pages:   189 | too_short: 32848 ( 50%) | correctable:  7540 ( 11%) |
unpaper + swt
  maybe:  5833 (  9%) | nb_words: 62309 | perfect: 17663 ( 28%) | garbage:   458 (  0%) | nb_pages:   187 | too_short: 31132 ( 49%) | correctable:  7223 ( 11%) |
ace
  maybe:  5128 (  8%) | nb_words: 62233 | perfect: 19172 ( 30%) | garbage:   468 (  0%) | nb_pages:   187 | too_short: 30765 ( 49%) | correctable:  6700 ( 10%) |
ace + unpaper
  maybe:  5017 (  8%) | nb_words: 61997 | perfect: 19307 ( 31%) | garbage:   494 (  0%) | nb_pages:   188 | too_short: 30667 ( 49%) | correctable:  6512 ( 10%) |
ace + swt
  maybe:  4973 (  8%) | nb_words: 59440 | perfect: 17441 ( 29%) | garbage:   480 (  0%) | nb_pages:   186 | too_short: 29897 ( 50%) | correctable:  6649 ( 11%) |
ace + unpaper + swt
  maybe:  5213 (  8%) | nb_words: 61464 | perfect: 18022 ( 29%) | garbage:   492 (  0%) | nb_pages:   187 | too_short: 30813 ( 50%) | correctable:  6924 ( 11%) |
```

### Explanation

I've run various combinations of image processing algorithms on my documents, then I've run Tesseract on each resulting image. I've then used Pyenchant to figure out how many words in each page appear in the dictionary (french).

### Algorithms

* raw : no processing, just tesseract
* unpaper : Unpaper's algorithms. See https://github.com/jflesch/libpillowfight#note-regarding-unpapers-algorithms
* swt : Stroke Width Transformation
* ace : Automatic Color Equalization. See http://argmax.jp/index.php?colorcorrect

### Output values

* nb_pages : number of pages analyzed with this combination
* nb_words : number of words found by Tesseract
* too_short : words too short to be meaningful for this test (less than 3 characters). May actually be garbage if there are a lot of them.
* perfect : number of words found in the dictionnary
* correctable : number of words that can probably be fixed (levenshtein distance with the first suggestion from pyenchant == 1)
* maybe : PyEnchant was able to provide suggestions. But none is really close to the original word found by Tesseract.
* garbage : PyEnchant wasn't able to provide any suggestion at all

### Note regarding SWT:

SWT should return only pixels where it thinks there is a letter. Thing is, with scanned documents at 300 dpi, strokes are often too small, giving very poor results. So instead, this SWT implementation figures out the box around each word, and return the boxes as is (see https://github.com/jflesch/libpillowfight#python-api-5 PF_SWT_OUTPUT_ORIGINAL_BOXES )

**Comment by jflesch** [comment]
Let's adjust the results a little bit.

Because of the crash, some algorithm combinations were applied on 187 documents, while others were on 188. So let's bring it back on 187 documents for each.

Also, let's drop the 'maybe' and the 'too_short'. There are meaningless for Paperwork.

```
raw
  nb_words : 65024 ; perfect + correctable : 26563
unpaper
  nb_words : 64850 ; perfect + correctable : 26442
swt
  nb_words : 64770 ; perfect + correctable : 25981
unpaper + swt
  nb_words : 62309 ; perfect + correctable : 24886
ace
  nb_words : 62233 ; perfect + correctable : 25872
ace + unpaper
  nb_words : 61667 ; perfect + correctable : 25681
ace + swt
  nb_words : 59759 ; perfect + correctable : 24219
ace + unpaper + swt
  nb_words : 61464 ; perfect + correctable : 24946
```

**Comment by jflesch** [comment]
Currently, my conclusion is that applying any image processing algorithm reduces the number of words found. On scanned documents, none bring any real improvement to the output of Tesseract.

I guess I could try to make some improvements on the SWT algorithm. For instance, I've been thinking about making 2 passes : one of the image as is to find the word boxes, and one on each of the boxes, but extended enough so the strokes are correctly detected by SWT.
But I have already spent far too much time on that (reminder: I make this on my free time).

--

However, I'll keep this ticket opened as a reminder : In the page editor, I want to include a button for ACE, and another button for Unpaper (or SWT?).

**Comment by jflesch** [comment]
ACE: See #228 

Export with Unpaper / SWT's algorithms:
https://github.com/jflesch/paperwork-backend/commit/9a804d7a6852b4f35ce39edbc9362b869301771b
99387e2921d7f884ee4c316a58d35e38aca16d3e
4522311b8633dbc7ac4e34c5c7b3af74f9378c5a
(seems to bring noticeable improvements only when exporting to PNG. I will have to check why it doesn't for PDF files)
