### ISSUE TITLE
No "Orientation detection" option

### ISSUE THREAD

**Issue by Yamakaky** [jflesch/paperwork#396]
In the settings panel, I don't have the "Orientation detection" option, like on [this page](https://github.com/jflesch/paperwork/wiki/OCR-orientation-detection). I only have the checkbox and the language selection option.
I use the french translation.

**Comment by jflesch** [comment]
My bad. This doc is not up-to-date.

This settings has been removed in the latest versions. Latest versions of Paperwork and Pyocr use an feature of Tesseract to detect the page orientation. This feature is fast and reliable, making this setting in Paperwork useless.

**Comment by Yamakaky** [comment]
Ok

**Comment by Yamakaky** [comment]
Ok

**Comment by Starch** [comment]
Please put back the setting for allowing to deactivate this option instead of update the documentation.

1. Even if "fast", it is still slower than doing the OCR once
2. In most of my cases, pages are already in proper orientation, and process is wrong about 80% of times, reorienting the scans and giving me extra work to reorient the pages.

**Comment by jflesch** [comment]
80% is totally abnormal. Which version of Tesseract and Pyocr do you use ?

**Comment by Starch** [comment]
Seems I have tesseract-ocr 3.04.00-5+b1 (debian stretch / testing) and pyocr 0.3.1 (my paperwork virtualenv).

Attached the result of pip freeze from inside my virtualenv.
[pwk.env.txt](https://github.com/jflesch/paperwork/files/112750/pwk.env.txt)

**Comment by jflesch** [comment]
Hm, weird. Can you run Paperwork from a terminal and paste here its output when an orientation is not correctly detected please ?

**Comment by jflesch** [comment]
I've just run test on Ubuntu (tesseract 3.04), and for portrait pages, it works fine for me.
However, people are telling me it doesn't work well with landscape pages ( #406 ).

Are you having this problem only with landscape pages, or with portrait pages as well ?

**Comment by Starch** [comment]
dectection goes wrong on portrait pages for me (i rarely scan landscape ones)
[paperwork.20160207-093114.txt](https://github.com/jflesch/paperwork/files/120631/paperwork.20160207-093114.txt)

. Here is the log.

**Comment by jflesch** [comment]
Is there anything specific to the documents that failed ? Is the background white for instance ?

**Comment by jflesch** [comment]
Also, would it be possible to have a copy of a document that failed ? (I would understand if not)

**Comment by trou** [comment]
I also have the bug from time to time. If I have an "innocent" page having the bug I'll post it.

**Comment by jflesch** [comment]
Regarding the detection problem, a fix has been made : https://github.com/jflesch/paperwork/issues/406#issuecomment-184619701 . It is included in 0.3.1.

For this ticket, I just intend just update the documentation.

**Comment by jflesch** [comment]
Documentation has been updated
