### ISSUE TITLE
Can't save paper

### ISSUE THREAD

**Issue by mjourdan** [jflesch/paperwork#400]
"New Document" is selected. I click "scan one page". After the orientation detection is done, I get this:

> Traceback (most recent call last):
>  File "/home/thamieu/Projets/paperwork/src/paperwork/frontend/mainwindow/__init__.py", line 4012, in __on_predicted_labels
>    self.upd_index(doc, new=True)
>  File "/home/thamieu/Projets/paperwork/src/paperwork/frontend/mainwindow/__init__.py", line 4016, in upd_index
>    self.refresh_docs({doc})
>  File "/home/thamieu/Projets/paperwork/src/paperwork/frontend/mainwindow/__init__.py", line 3451, in refresh_docs
>    rowbox = self.lists['doclist']['model']['by_id'][doc.docid]
> KeyError: '20151008_1859_49'

Paperwork 0.3-unstable

**Comment by mjourdan** [comment]
Wait... Seems now that I could save my paper. Perhaps this is a false alarm :/ I'll try more.

**Comment by mjourdan** [comment]
I confirm this bug. I selected the "new document" entry and used "scan from feeder", this time. My page is showed but my document list hasn't been updated with my new paper. I selected an older paper, to see what happens. I actually can browse any of my existing paper, but the very latest. Selecting "new document" again doesn't help to retrieve the freshly scanned page.

**Comment by jflesch** [comment]
I'm going to assume this is for unstable.

**Comment by jflesch** [comment]
Fix: a591792a04e46a7db3866fd7988a1d5e09880683 (it interrupted the multiple scans process)

**Comment by jflesch** [comment]
Please reopen if you still have problems.
