### ISSUE TITLE
Long delay after orientation detection

### ISSUE THREAD

**Issue by mjourdan** [jflesch/paperwork#401]
I scan one page from lid.

Orientation detection is done correctly (see the "Detected orientation" message in the terminal, but Paperwork still show the 4 possible orientations. It takes several seconds before the right view is show. Also, during this time, it lacks some visual clue that something is happening.

> WARNING paperwork.frontend.util.canvas.animations Spinner icon not available
> INFO   paperwork.frontend.mainwindow.scan Detected orientation: 180
> WARNING paperwork.frontend.util.jobs   Job OCR:0 took 19907ms and is unstoppable ! (maximum allowed: 500ms)
> INFO   paperwork.frontend.mainwindow  Showing document 20151008_1912_26

**Comment by jflesch** [comment]
Which version ? stable or unstable ?

**Comment by jflesch** [comment]
I'm going to assume this is for unstable.

**Comment by jflesch** [comment]
>  it lacks some visual clue that something is happening.

> WARNING paperwork.frontend.util.canvas.animations Spinner icon not available

Paperwork uses the icon theme from Gnome. Here it is looking for the icon "process-working" in size 48x48 and didn't find it. So it was unable to give you a visual clue.

**Comment by jflesch** [comment]
Based on your screenshot in another ticket, you're obviously using Gnome. I fear the icon may have another name in the latest version (I'm using Gnome 3.14.1)

**Comment by mjourdan** [comment]
Yep, this report is against unstable.

I'm running fedora 22 with adwaita-icon-theme-3.16.2.1-1.fc22.noarch

I noticed the following message in adwaita-icon-theme news file, for 3.13.3:
>  - spinner that only scales up to 32

So, I guess this is more likely a scale issue than a name change.

**Comment by jflesch** [comment]
Good catch. I guess I will to scale it in Paperwork (32x32 is by far too small)

**Comment by jflesch** [comment]
Fix for the icon: ded3c1649871a1bf8db2d2c484226093ee962412 (will load 32x32 icon and scale it to 64x64).
Please reopen if you still have problems
