### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#404]
> @jflesch rel. use cases: most of my labels are thus coloured: CPAM, Société Générale, Materiel.net, Amazon, Orange, etc. I open the web site, and color-pick the dominant colour of the page.
This allows very fast thumbnails scrolling when you're looking for a particular document!

A color picker could help. See the color selector in Gimp for reference.

**Comment by tYYGH** [comment]
In version 0.2.x, there _is_ currently a color picker ;-)

**Comment by jflesch** [comment]
Duly noted :)

**Comment by tiramiseb** [comment]
There is already one in 0.2, so... issue #404 not found ? :)

**Comment by jflesch** [comment]
Note to myself: see libgtk-3/gtk/deprecated/gtkcolorsel.c (functions mouse_release(), key_press() and get_screen_color(), and grab_color_at_pointer()) for reference

**Comment by jflesch** [comment]
Done: 02ab5754ebfcb611d8e972fb5534561b15e8121a
(this X/Gtk hack is ugggllly ... but well, it works)
