### ISSUE TITLE
Too many file descriptors opened

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#405]
Today, I git pull’ed paperwork/stable before using it. It may be a coincidence (a threshold passed), but now I have lots of:
```
INFO   paperwork.backend.common.doc   Changing docid: /ici/partage/Papiers/20151009_2009_47 -> /ici/partage/Papiers/20120229_0000_01_01
INFO   paperwork.frontend.doceditdialog Extra text unchanged
INFO   paperwork.backend.docsearch    Indexing new doc: 20120229_0000_01_01
INFO   paperwork.backend.docsearch    Fitting estimator with doc: 20120229_0000_01_01 
INFO   paperwork.backend.docsearch    Index: Commiting changes and saving estimators
INFO   paperwork.frontend.mainwindow  Searching: []
INFO   paperwork.backend.docsearch    Index: Reloading ...
INFO   paperwork.frontend.mainwindow  Searching: []
INFO   paperwork.frontend.util.actions Action: [Open selected document]
INFO   paperwork.frontend.mainwindow  No document selected. Can't open
INFO   paperwork.frontend.util.progressivelist List 'documents' : 100 elements displayed (100 additionnal)
ERROR  root                           Exception while trying to get the number of pages of '20080818_0000_01': [Errno 24] Trop de fichiers ouverts: '/ici/partage/Papiers/20080818_0000_01'
Traceback (most recent call last):
  File "/ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/frontend/mainwindow/__init__.py", line 3187, in on_search_results_cb
  File "/ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/frontend/mainwindow/__init__.py", line 3274, in __get_doc_model_line
  File "/ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/backend/common/doc.py", line 88, in __get_nb_pages
  File "/ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/backend/img/doc.py", line 258, in _get_nb_pages
OSError: [Errno 24] Trop de fichiers ouverts: '/ici/partage/Papiers/20080818_0000_01'
ERROR  paperwork.frontend.util.jobs   ===> Job DocThumbnailer:2 raised an exception: <type 'exceptions.IOError'>: [Errno 24] Trop de fichiers ouverts: u'/ici/partage/Papiers/20151008_2130_21/paper.1.jpg'
ERROR  paperwork.frontend.util.jobs    0: /ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/frontend/util/jobs.py: L  178: _run
ERROR  paperwork.frontend.util.jobs    1: /ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/frontend/mainwindow/__init__.py: L  785: do
ERROR  paperwork.frontend.util.jobs    2: /ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/backend/common/page.py: L  175: get_thumbnail
ERROR  paperwork.frontend.util.jobs    3: /ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/backend/common/page.py: L  145: __make_thumbnail
ERROR  paperwork.frontend.util.jobs    4: /ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/backend/img/page.py: L  139: __get_img
ERROR  paperwork.frontend.util.jobs    5: /usr/lib/python2.7/site-packages/PIL/Image.py: L 2288: open
ERROR  paperwork.frontend.util.jobs   ---> Job DocThumbnailer:2 was started by:
ERROR  paperwork.frontend.util.jobs    0:      src/launcher.py: L   27: <module>
ERROR  paperwork.frontend.util.jobs    1: /ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/paperwork.py: L  111: main
ERROR  paperwork.frontend.util.jobs    2: /ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/frontend/mainwindow/__init__.py: L 3829: __on_doc_lines_shown
ERROR  paperwork.frontend.util.jobs    3: /ici/home/yves/.local/opt/paperwork-stable/paperwork/src/paperwork/frontend/util/jobs.py: L  247: schedule
```

**Comment by jflesch** [comment]
How many documents / pages do you have ? (there is a script in Paperwork repository that can answer this questions : scripts/stats.py)
Are they mostly PDF or image documents ?

**Comment by jflesch** [comment]
There has been a bug related to PDF for a long time : Libpoppler is not thread-safe when it comes to opening or closing PDF files --> I decided to keep them open pretty much all the time.
Maybe this is what caused your problem (but it implies you have >= 65500 PDF files ?)

Anyway, I pushed a fix: 674c69afa57835e59ebc780947d939e7de881942
I hope it won't make things too unstable :/

**Comment by jflesch** [comment]
I need to do more testing, but it seems my workaround is not required anymore. And hopefully it will fix your bug.

**Comment by tYYGH** [comment]
```
Statistics
==========
Total number of documents: 1234 (332 of which are PDF documents)
Total number of pages: 2819
Total number of words: 558583
Total words len: 3929706
Total number of unique words: 67017
===
Maximum number of pages in one document: 86
Maximum word length: 222
Average word length: 7.035134
Average number of words per page: 198.149344
Average number of words per document: 452.660454
Average number of pages per document: 2.284441
Average number of unique words per document: 247.160454
Average accuracy of label prediction (global): 98%
Average accuracy of label prediction (positive): 84%
Average accuracy of label prediction (negative): 99%
```
FYI, I noticed that the bug happened mostly after I changed the date of a document from the present day (the day when the document is scanned) to a long past date (between 2008 and 2013 usually).

Next time I scan documents, I’ll upgrade, and I’ll let you know if the bug is gone. Thanks.
By the way, the bug is not blocking. I can quit&relaunch Paperwork and continue my work…

**Comment by tYYGH** [comment]
Sorry, wrong button :-/

**Comment by tYYGH** [comment]
With latest stable code git-pull'ed, the problem seems to be gone. I don't know if this is through a commit you made, or thanks to a system update, but I don't have the error any more. Nice :)

**Comment by jflesch** [comment]
Probably my commit. I just hope it remains stable

**Comment by tYYGH** [comment]
I'm sorry I have to reopen this. The problem is still there. I could reproduce it again and again by trying to run the OCR on a >20-page document from a PDF file, and failing each time.

The issue is with ulimit's max opened files, the default value of which was 1024 on my system. By looping over ```ls -1 /proc/<pid of python>/fd | wc -l```, I could see the value mostly grow and sometimes decrease a bit as OCR ran page after page. Paperwork stopped OCR'ing and threw an ERROR exactly when the above command showed ```1024```.
I also noted that:
— the above counter tended to soar while OCR'ing full-page tables with plenty of cells;
— the counter tended to stay high after an OCR finished, instead of coming back to its initial value.

I ended up rebooting, after having changed the ulimit's hard and soft limits to 8192. Then I was able to run the OCR on this PDF file.

@jflesch Je ne souhaite pas publier ce fichier PDF car il contient des noms de copropriétaires, mais tu peux me le demander par mail à l'adresse ```pw_jf``` at ```yalis.fr```.

**Comment by tYYGH** [comment]
Probably related to #142.

**Comment by jflesch** [comment]
Fixed in branch 'unstable': 35e4220ad35810454c45374051fc17c91a4d0dab
Backported in branch 'stable': 2b886e4dc6ad65d19fa3fa7df35e5402bcef40df but there are still some leaks that don't appear in the branch 'unstable'.

I don't think it's worth I spend more time fixing it in the branch 'stable'.

Please reopen if you still have problems.

**Comment by tYYGH** [comment]
Perfectly understandable ;-) Thanks for the fix, and the partial backport!

How would you rate the “unstable” branch for daily usage involving important documents?
I’m perfectly aware that no program can be considered fail-safe, and I do have backups. What I wish to know is if the differences in “unstable” make it more likely than “stable” to silently loose documents, or not.
Said differently, I’m completely willing to use unstable as long as basic operation is possible, even if that means having more bugs and reporting them, but I don’t want to loose documents without noticing…
What do you think?

**Comment by jflesch** [comment]
It won't loose documents without you noticing (it never did for me anyway).

Afaik, the worst that could happen is for instance loosing a page of a document when trying to move it. Or having label changes not actually applied.
In other words, things that you should see immediately, or soon after restarting Paperwork.
