### ISSUE TITLE
Fujitsu ScanSnap 5110 Scanner

### ISSUE THREAD

**Issue by Jfleschwyplay** [jflesch/paperwork#409]
From Hartmut Eilers <hartmut@eilers.net>:

> ich have a Fujitsu ScanSnap 5110 Scanner and try to use Paperwork 0.2.4
> on top of Ubuntu 14.04.
>
> My Problem is that all scans have their end cut off. I checked with xsane that it is not an issue with my scanner, if I set the scan width to 21x29cm the whole page is scanned. In paperwork code it seems that you ask the scanner for his default size and just scan that. So I assume that my scanner has a default scan height of letter but I'm scanning A4 papers. Is there a chance to set the scan height in paperwork so that it scans the full paper height ?

**Comment by tYYGH** [comment]
My question may be a bit obvious, but did you try to calibrate the scan area in the settings?

**Comment by lnetwalker** [comment]
I did the calibration. It does exactly the same, scans a letter size document and allows me to setup a smaller crop size.

**Comment by lnetwalker** [comment]
your patch did the trick,
after applying the patch to the latest release, I entered the calibration
and cropped to the maximum size.
All Documents are now scanned perfectly.

**Comment by jflesch** [comment]
Commit: 3fa737a1e21b9e183489adf9b40583fb0454eefa (on branch 'stable' and 'unstable')

**Comment by jflesch** [comment]
Thanks for your bug report. Please don't hesitate to reopen this ticket if you have any other issue with your scanner.
