### ISSUE TITLE
[unstable] regression in labels caused by os.path.sep

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#410]
Due to #362, commit https://github.com/jflesch/paperwork/commit/4a9c68625d62abfc8cde9f1f4075185151e590f3 caused a regression:
I have labels “copropriété: devis”, “copropriété: appel fonds”… and the ```:``` is crashing Paperwork while scanning all documents’ labels.
More specifically ```assert(os.path.sep not in label_name)``` in labels.py:192.

I don’t mind loosing the ```:```, so I ran
```
grep -lF 'copropriété: ' $papers/*/labels | while read f; do sed -ri 's/^copropriété: ([^,]*),/copropriété \1,/' "$f"; done
```
but other people will encounter this problem…
Maybe some kind of automatic migration would do the trick (with an alert explaining why the ```:``` disappeared).

**Comment by jflesch** [comment]
hm, I think I can fix that easily. I will use the hash of the label.

**Comment by jflesch** [comment]
ee5a4a6691568d7c8be87548ecf366ed6d316033
Please reopen if you still have problems :)
