### ISSUE TITLE
[unstable] How do I reset the indexes?

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#411]
With unstable as of right now, Paperwork doesn’t know about my labels anymore. Past documents still have their labels, thankfully, but I cannot apply existing labels to any new document, because the labels list is empty. I guess I screwed up after #410, so how would I go about a clean start? I tried simply removing ~/.local/share/paperwork (I have a copy), but that is not enough.

**Comment by jflesch** [comment]
I think getting the fix from #410 + running ```rm -rf ~/.local/share/paperwork``` should solve this problem

**Comment by jflesch** [comment]
Is it ok for you now ?

**Comment by tYYGH** [comment]
Yes, now with unstable, I get my labels, whether I remove ```~/.local/share/paperwork``` or not.
However, I immediately gave up using unstable, because it is too much… well… unstable ;-)
Keep up the good work, I'll open some feature-requests, based on my short observations.
