### ISSUE TITLE
feature request: possibility to enter date with keyboard

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#412]
When I switch to a document's properties (date, labels, and additional keywords), and I wish to change the date to eg. ```27/03/1998```, I have to open the calendar, and click 17 times on the "previous year" button, and then 8 times on the "previous month" button, and finally click on the day number. That's 27 clicks!
I wish I could just type the date using the keyboard, as in the stable branch (with the extra bonus that 2-digit years are auto-transformed to 4-digit years).

**Comment by jflesch** [comment]
Actually, there are keyboard shortcuts integrated in the GtkCalendar:
- Ctrl-left / Ctrl-right : change the month
- Ctrl-Up / Ctrl-Down : change the year

(you may have to click somewhere on the calendar here).

I understand changing quickly the month and year is useful when scanning the documents you already have. But once that's done, that's something you never do again.
So I don't think it's worth changing the UI for that. I think just updating the doc should be enough.

**Comment by tYYGH** [comment]
I admit that this point of view is sensible.
However, importing many old documents into Paperwork will be a pain… unless there is a fix to the #214 feature request ;-)

**Comment by jflesch** [comment]
Here is what I'm going to do:
- I'll move the ticket to 0.4.x
- I'll release 0.3.0 as-is.
- If enough people request this change, I'll move back this ticket to 0.3.x (maybe 0.3.1)
- If not, either I implement it for 0.4.x or I don't implement it at all.

**Comment by mjourdan** [comment]
This should not happen very often but I agree with @tYYGH it is still a very annoying flaw. This [old mockup](https://github.com/mjourdan/gnome-design/blob/master/paperwork/wires/first-paper.png) suggests keyboard as the primary interface to specify the date.

**Comment by jflesch** [comment]
Hm, ok, I guess I can switch the field from readonly to readwrite and reparse the user input :)

**Comment by jflesch** [comment]
https://github.com/jflesch/paperwork-backend/commit/06c9ef700a2a0e3fa6f25c96b7c34133474f1bbd
34a1513e8b4dda8309a4bc20271ad83c3a17f859

Here is how it goes:
* As long as the date in the entry field is the same than the current one, the field has its text in black and gray~white background
* When the date in the entry field is different from the current one:
  * Either it can be successfully parsed, in which the field has its text in black and green (but not too green) background
  * Or it can't be parsed, in which case the field  has its text in black and red (but not too red) background

As long as the date is invalid (red background), the change can't be validated. Each time the user tries to validate it, a popup will appear saying "no can't do".

**Comment by tYYGH** [comment]
Thank you!
