### ISSUE TITLE
Page rotation + cropping

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#418]
Both at the same time are not easy

**Comment by mjourdan** [comment]
What do you mean?

**Comment by jflesch** [comment]
It's a bug. Try to edit a page : start cropping the page, then rotate it *before* validating. You will see the display is mess.

**Comment by jflesch** [comment]
f63152de919fee54c5500f44bc33551e3334f078
52a841029c86a170deb42087e61b12f51709dbbb
4cb10a70e39bf2ce2665afc870c8c5c84ce714a5
d8e75cd0f75fcf7024057b53feed763ac855c4ce
839a7d853469f79c80e71754bc5d52e0de5cdc10
4d46a75af0451a082fc8172ee2a17ed082dba968
5c644e85de688c9c091e595182bbb10dbf0aadc1
22cdf79b833e83fc9b756f50ac9a10fb19ba9f9a
154d99fdb6def62e15b1ccceba2c841c0d966f1c
(well, that was quite a painful fix ...)
