### ISSUE TITLE
Can't scan new page

### ISSUE THREAD

**Issue by mjourdan** [jflesch/paperwork#424]
I just could successfully scan a first page, a second one, but the third failed. Scan happens, but the page is not saved. I tried with a new document, same problem.

We have the following errors (please see the [attached file](https://github.com/jflesch/paperwork/files/73301/bug_cant_scan_new_page.txt)  for more debug output):

>  File "/home/thamieu/Projets/paperwork/src/paperwork/frontend/mainwindow/__init__.py", line 2727, in compute_zoom_level
    total_width = sum([page.size[0] for page in other_pages])
AttributeError: 'NoneType' object has no attribute 'size'

This happens with the 0.3 'unstable' branch.

Steps to reproduce:
- open a document with two pages
- scan a third page
- no way to save this page in any document

As a workaround, I had to close paperwork, scan directly the page in a new document, then use drag'n'drop to move the page to the right document.

**Comment by jflesch** [comment]
1) Ok, should be fixed: 5ff880c3d8b4195a694cf98b57e77efe97cca3fc
2) Please don't truncate the stacktrace. Here luckily, I had enough information. But something the whole stacktrace is required
3) Please work with branch 'testing' for now (sometimes, I forget to push the fixes in the branch 'unstable' and only do it much later)

Anyway, thanks for your bug report :).
Please reopen this ticket if still have problems.
