### ISSUE TITLE
Wrong number of pages

### ISSUE THREAD

**Issue by mjourdan** [jflesch/paperwork#425]
After moving one page from one document to another, the page counter of the latest document produces odd results: it indicates I'm reading page 3/1 (instead of 3/3).

Using paperwork 0.3 'unstable'.

Steps to reproduce:
- move one page from one document to another
- select the document holding the page you just moved
- take a look at the page counter; it indicates 1/1
- scroll down to reach the second page, then the third
- counter indicates 3/1

**Comment by jflesch** [comment]
Not reproduced here :/
Are you up-to-date ?

(PS: Please work with the branch 'testing' for now please)

**Comment by mjourdan** [comment]
Sorry for replying so late. I didn't notice there was a testing branch by the time I tried. I tried against it and could not reproduce the bug either. So, I close this ticket. Thanks.
