### ISSUE TITLE
RFE: provide a docker

### ISSUE THREAD

**Issue by kforner** [jflesch/paperwork#429]
Hi,
If you provided a docker, it would solve the installation on all platforms, and it would help debug user problems since you would be able to reproduce the exact user setups. 
What do you think ?
Karl

**Comment by jflesch** [comment]
Someone has already started working on it :
https://groups.google.com/forum/#!topic/paperwork-gui/pwETR9NoXO4

I, for one, am not going to work on it (I don't have enough free time to work on it, and I'm not interested anyway). And, IMHO, it's like making packages for each GNU/Linux distribution. It's simply out of the scope of this project.

If you want to make a Docker container, feel free to do it. I'll gladly add a link in the documentation to your container.

**Comment by kforner** [comment]
ok, I'll have a loot at it, thanks.
