### ISSUE TITLE
fix: ubuntu installation instructions

### ISSUE THREAD

**Issue by kforner** [jflesch/paperwork#430]
I had to run this, otherwise `sudo pip install numpy scikit-learn` did not work:
```
sudo apt-get install python-scipy libfreetype6-dev

```

**Comment by z0u** [comment]
These packages are also required for Debian Jessie, and are missing from the instructions. `python-scipy` is needed for building `scikit-learn`, and `libfreetype6-dev` is needed for building `matplotlib`.

**Comment by jflesch** [comment]
Hm, I think I'm going to reply the same thing than for #431 :
- 0.3.0 won't need all those annoying dependencies anymore
- I hope to release 0.3.0 at the end of this month

So I think it's not worth spending much time one those issues. But thanks anyway for taking the time of reporting them.

(PS: If you want to have fun, 0.3.0 is currently in the branch 'testing' :) )
