### ISSUE TITLE
does not run

### ISSUE THREAD

**Issue by trenkert** [jflesch/paperwork#432]
terminal output:

File "/usr/local/bin/paperwork", line 3, in <module>
    from paperwork.paperwork import main
  File "/usr/local/lib/python3.4/dist-packages/paperwork/paperwork.py", line 31, in <module>
    from frontend.mainwindow import ActionRefreshIndex, MainWindow
ImportError: No module named 'frontend'

and paperwor-chkdeps gives:

[ERROR] Expected python 2.7 ! Got python 3.4.4.final.0

**Comment by jflesch** [comment]
https://github.com/jflesch/paperwork/wiki/Contact#bug-trackers

**Comment by jflesch** [comment]
I didn't have much time to reply. So, to clarify my previous reply, your ticket lacks a *lot* of informations.
Can you at least tell me on which GNU/Linux distribution you installed Paperwork and how ?

**Comment by jflesch** [comment]
By the way, it seems you're starting Paperwork using Python 3. At the moment, Paperwork only supports Python 2.7.

**Comment by jflesch** [comment]
Also, which version of Paperwork ?

**Comment by trenkert** [comment]
sorry, I got it to work by running the 0.3 beta. It is quite an impressive app! I only notice that documents only appear by dates not names; and page/word highlighting only worked at the beginning, now it does not highlight anything. Other than that, the speed and accuracy is really good!

**Comment by jflesch** [comment]
1) The idea with showing only the dates is "why bother giving them a name ?". The name is usually on the paper, so the OCR can pick it up, and you can search for it easily. If you really want, you can rename the folders in your work directory, Paperwork should then display as-is. However, documents won't be sorted correctly anymore.

2) Page/word highlighting may take a few seconds to load (it's a CPU-heavy operation, so it's delayed). If you have to wait more than 10 seconds, there is a bug.

**Comment by trenkert** [comment]
1) I see your point. However, I personally would like this option to either show the date or the file name (or the tags) as the "identifier" for the document overview. 

2) It works when I click "redo ocr". But documents that have been scanned before only sometimes show highlighting.

**Comment by tYYGH** [comment]
@trenkert:
1) Considering how this application works, I fail to see what you would call the "name of a document". I see no way for Paperwork to deduce this information. Does this mean that you're willing to give a "title" to each document, in addition to the auto-found words, and in addition to the labels, and in addition to the keywords you may already add? If so:
* What enhancement in usability would you expect from the displaying of the title, in addition to the date and labels that are already displayed?
* What use cases would the title allow, that the current interface does not?

_Note: I don't develop Paperwork; I'm just a heavy user of it, who got very interested in Paperwork_

**Comment by jflesch** [comment]
1) I have no use for it, and I don't develop things I don't use --> not going to happen (not by me anyway)
2) This is weird.

I'm going to focus this ticket on point 1.

**Comment by jflesch** [comment]
Actually, this ticket is becoming messy. I'm making a new one : #436.
I'm closing this one.

**Comment by trenkert** [comment]
@tYYGH When I scan a lot of documents on the same day, and with similar words in them, it would make a big difference for me if I was able to manually asign a name to each document (as an option). I had the problem of scanning >300 pages across ~70 documents on one day and would have loved to simply type in a filename that is displayed by Paperwork. 

But if you think of a more "archival" approach, it would make sense to be able to manually provide some metadata like original date (not the date of the scan), original author and so on. I don't see how this could all be covered by using tags.
