### ISSUE TITLE
Mint 17 & Paperwork 0.3: Install Error

### ISSUE THREAD

**Issue by scubbx** [jflesch/paperwork#439]
When installing Paperwork 3 on Linux Mint 17, the following error appears: 

`error: can't copy 'src/paperwork/frontend/application.css': doesn't exist or not a regular file`

This happens when using pip, pypi-install and when installing directly from the git repository.

**Comment by jflesch** [comment]
When installing from the git repository, can you give me the exact command you use please ?

**Comment by jflesch** [comment]
Fixed : 853640bb003262a5e601d35e17439e077ed974fe
I've released a version 0.3.0.1 including this fix.
Sorry for the inconvenience.

**Comment by scubbx** [comment]
Installation works now, thank you very much!
