### ISSUE TITLE
Paperwork 0.3 not starting in Mint 17

### ISSUE THREAD

**Issue by scubbx** [jflesch/paperwork#440]
When running Paperwork 3, the following error is displayed:

`TypeError: object of type 'GtkSettings' does not have property 'gtk-decoration-layout'`

Maybe there is a GTK version conflict?

**Comment by jflesch** [comment]
Can you tell me which version of Gtk is installed on your system ?

**Comment by jflesch** [comment]
FYI, on Debian stable:

```
$ apt-cache show libgtk-3-0                         
(...)
Version: 3.14.5-1+deb8u1
```

**Comment by jflesch** [comment]
Actually, I found the answer myself: http://packages.linuxmint.com/search.php?keyword=libgtk-3-0&release=any&section=any (Linux Mint 17.3 = Rosa)
You have Gtk 3.10.

[```gtk-decoration-layout``` appeared in Gtk 3.12](https://developer.gnome.org/gtk3/stable/GtkHeaderBar.html#GtkHeaderBar--decoration-layout)

**Comment by jflesch** [comment]
So in short, Linux Mint has packages even older than Debian stable ... I .. I didn't know it was possible ... ;)

More seriously, I just can't support too old versions of Paperwork's dependencies. Afaik, most opensources projects actually work and test only with packages >= Debian Testing. It's too much work doing otherwise.

In this specific case, I can workaround easily, so I will. But if there are any more problems due to dependencies too old, I'm sorry but you will be on your own (in other words, stuck with Paperwork 0.2.x).

**Comment by jflesch** [comment]
Workaround : ba781e3a5d1cb093008a4b07e902f686dea66306
Please reopen this ticket if this workaround doesn't actually work.

**Comment by scubbx** [comment]
Thanks for the patch, but it seems that the version-dependency issues go deeper. The UI files also have a version number - now this error is displayed

`gi._glib.GError: src/paperwork/frontend/mainwindow/mainwindow.glade: required gtk+ version 3.14, current version is 3.10`

The reason for Mint 17 having older packages might be because it is based on the latest LTS release of Ubuntu which dates back to mid-2014.

**Comment by jflesch** [comment]
What you can try is to edit src/paperwork/frontend/mainwindow/mainwindow.glade, and just replace "3.14" by "3.10". If it works, I can also apply this change.

(I could test it myself, but I would have to download the iso and install a VM I may never use again ...)

**Comment by scubbx** [comment]
A possible workaround could be to use the (experimental?) **Docker image**. It might not be the most comfortable solution, but it is certainly better than a virtualization and everybody can stay with the preferred OS. :-D
**But**: It is not yet working correctly, since it does not show the contents of the selected document. (I just want to take a note of this here in case someone with more experience with Docker stumbles upon this note and is able to fix this)

The steps I took to install the Docker container on Linux Mint 17 were:

* Install Docker using this guide https://docs.docker.com/compose/install/ and thereby also install docker-compose (I had to manually install the packages **apparmor** and **cgroup-lite**). Make sure that the Docker service is running: `sudo service docker status`.

* Clone the paperwork-docker git repository: `git clone https://github.com/kschwank/paperwork-docker`

* In the terminal inside the freshly cloned git repository, switch to the unstable branch: `git checkout unstable`

* Assuming we already have a papers folder, we have to link our existing papers folder with the one inside the container for paperwork to have access to it. To do so, open the file `docker-compose.xml` in the root of the git repository and add a line, similarly to this one at the end: `- /home/USER/papers:/home/paperworker/papers` . The part before the colon is the path on your current file system, the part after it describes the path inside the docker image. This second part is hardcoded, so there is no need to change this one.

* With the command `sudo docker-compose up` executed inside the paperwork-docker git-folder, the docker image is created, Paperwork and its dependencies are compiled and the program itself executed. The first startup takes a while.

* At least on my machine, all existing documents are displayed - now it is only necessary to make the actual documents appear. ;-)

**Comment by jflesch** [comment]
Did you try just changing the version number in the .glade files ? If you're lucky, it may be enough.

Regarding the Docker container, I guess a LXC container could also do the trick. I tend to prefer LXC containers because of their simpler approach, but meh, whatever float your boat.

Note that currently, you don't have to switch to the unstable branch. Right now, 'stable' and 'unstable' have pretty much the same content (I haven't really started working on 0.4.0/unstable yet).

**Comment by scubbx** [comment]
Yes, I tried changing the version string, but then other errors appear ...

If I don't switch to unstable, the version of paperwork is 0.2.4 (!) Don't ask me, according to the Dockerfile, it should be the current stable branch of this repository - an excerpt of the "stable" branch Dockerfile:

```
RUN git clone https://github.com/jflesch/paperwork.git
WORKDIR /paperwork
RUN git checkout stable
RUN ./setup.py build
```

Looks like a mix-up on my part, but this is a different problem I guess, since it boils down to version 0.3.x not displaying the content of the selected paper.

**Comment by jflesch** [comment]
I think it's because Docker keep a cache of the result of each command. If you don't change the command (here ```git clone```), it won't execute it again. It will start immediatly from the Docker image that resulted from this command.

**Comment by colszowka** [comment]
Just came here to say that this also happens on Ubuntu 14.04, which is the still-current LTS release of the distro, so actually many people will probably be bumping into this (at least until 16.04 LTS ships in 2 months and all the non-adventurous people like me will upgrade to that).

Possibly Mint has the same issue as it's based off Ubuntu LTS?
