### ISSUE TITLE
Does not work with python3 but pip allow to download it

### ISSUE THREAD

**Issue by alexandrenorman** [jflesch/paperwork#450]
`pip3 install paperwork
`
download it but as it does not work, `setup.py` should contains something like :
`install_requires=['python<3'],
`
to prevent useless download.

**Comment by jflesch** [comment]
Agreed.
I guess the other option is that I finally port Paperwork to Python 3 :-). AFAIK, there are no more blocking dependencies (I need to check again).

**Comment by jflesch** [comment]
The branch 'unstable' is now python3-ready + python3-only.

What you suggest seem to work with Python 2.7 (branch 'stable') but for some reason, not with Python 3.x (branch 'unstable') :/

**Comment by jflesch** [comment]
It made troubles even with Python 2.7 --> Removed: 2c1915409d8ba01ce5d17c782b7564d9c642d814 .
I don't think there is any clean way to do that. The only way would be something like http://stackoverflow.com/a/13385468/5119781 , and it would still download the package first.

So I'm closing this ticket. If you have a better solution, feel free to reopen.
