### ISSUE TITLE
File structure with backend

### ISSUE THREAD

**Issue by Morosko** [jflesch/paperwork#451]
Like you explained to me in another issue in your backend repository I've added the remote and pulled. Now i got the following file structure:
```
paperwork/
    scripts/
        paperwork
    src/
        paperwork/
            backend/
            frontend/
            webend/ (my work)
```

When I now start paperwork it gives me `ImportError: No module named 'paperwork_backend'`, but paperwork.backend works. Could it be that your directory is named paperwork_backend? Is this by mistake or intentional? The directory in the backend repo is also named just backend, so what should I use?

**Comment by jflesch** [comment]
Why did you merge the trees from both repositories ? oO
I though your suggestion was only about managing changes between stable and unstable branches of Paperwork-gui/Paperwork-backend (which was surprising to me, since it's usually only me who takes care of that).

The usual way to do things is to setup a [virtualenv](https://virtualenv.readthedocs.org/en/latest/). Something like :

```
$ sudo apt-get install virtualenv python3-virtualenv
$ virtualenv -p /usr/bin/python3 dev_env
$ cd dev_env
$ source bin/activate
[dev_env] $ git clone git@github.com:jflesch/paperwork-backend.git
[dev_env] $ cd paperwork-backend
[dev_env] $ python3 ./setup.py install
[dev_env] $ cd ..
[dev_env] $ git init your_project
[dev_env] $ cd your_project
[dev_env] $ python3
>>> from paperwork_backend.docsearch import DocSearch
```

(Note that I don't usually use virtualenv. I just install paperwork-backend directly on my machine with ```sudo python3 ./setup.py install```)

**Comment by jflesch** [comment]
Basically, just treat paperwork-backend as you would treat any other dependency.

**Comment by Morosko** [comment]
In the other (issue)[https://github.com/jflesch/paperwork-backend/issues/1] you said:
> - clone one of the repo
- use git remote add to add the other one
- git pull

so I did it and I ended up with the described file structure^^

So I have to install the backend via pip or manually ?

**Comment by jflesch** [comment]
Hm, weird, ```git pull``` alone shouldn't have merged the trees (unless you specified ```git pull <the new remote>```. Anyway sorry, I guess my explanations weren't really clear.

Regarding paperwork-backend, right now you can't install it via pip because I haven't made any release yet. You will have to install it manually.

**Comment by Morosko** [comment]
No git pull alone didn't merge the two, but i copied the directory.

But anyway thanks again, I'll use it like you said now. :)
