### ISSUE TITLE
Multiple Export

### ISSUE THREAD

**Issue by gjelsas** [jflesch/paperwork#470]
how about a multi-export feature? Export everything in a time range or with a defined tag.

**Comment by jflesch** [comment]
Do you have any concrete use case ?

**Comment by gjelsas** [comment]
Yeah, in Germany the tax declaration is upcoming soon. So I want to quickly spill out all files tagged with Tax 2015!

**Comment by gjelsas** [comment]
In the meantime I created a python script to do the label or word based exports. It needs adaptations to your configuration of export direcory and paperwork directory, but otherwise works.

I put it here:
[paperwork-multiexport](https://github.com/gjelsas/paperwork-multiexport)

I'm not a good coder, so improvements are welcome!

**Comment by jflesch** [comment]
I think I'll simply allow selection of mulitple documents (with Ctrl / Shift). I just need to figure out how to present the export dialog in a clear manner.

**Comment by jflesch** [comment]
https://github.com/jflesch/paperwork-backend/commit/2e90247952b79f2558a613419e74b285c24bc079
def8e4fa4dfdd38aecf148255f57e828977946fc
bc8fa0773e0234413bfffaed7079ecb4106e7212
2fafbda91d0c20889c62be038cbe0946d5d41ebb

In the next version, it will be possible to select multiple documents using Ctrl+click, Shift+click, Ctrl+a, etc.
When using the option export->document(s), if there are many documents selected, it will ask for a folder when to store the exported documents.
Only exporting multiple documents to PDF is supported.

**Comment by jflesch** [comment]
See #496 for future GUI improvements
