### ISSUE TITLE
Please don’t force fullscreen

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#471]
Since my latest git pull (2016-04-07), Paperwork always starts fullscreen. Why?
Previously, not only did it _not_ start fullscreen, but also it did remember its window size, which it does not anymore…

**Comment by jflesch** [comment]
There has never been any forcing of the fullscreen resolution. When Paperwork is restarted, it recreated the main window with the same size it had when it was last stopped. I have never changed this code, and it's by far older than the 0.1.

However, if you're using Gnome 3, note that it has a really annoying behavior:
When a new main window is created and request a size &gt; x% of the screen, Gnome shell maximizes the window. For instance, you can check see the very same behavior with Gedit.

**Comment by tYYGH** [comment]
Tested. Confirmed. That was Gnome’s fault.
The same day I git pull’ed, I remote-displayed Paperwork on a laptop. When I opened Paperwork again and adjusted the window’s size, I guess I made it a bit bigger than it formerly was, which probably triggered Gnome’s “feature”…
