### ISSUE TITLE
[RFE] Setting date of Scanned Document

### ISSUE THREAD

**Issue by spaetz** [jflesch/paperwork#475]
Currently changing the date of a scanned document requires me to click the date button and to select a date in the calendar widget (using a double-click). All I want to do sometimes is to change e.g. a "13" to a "11" and I would like to simply type that (deleting stuff with backspaces and old-fashioned things like that).
Would it be possible to make the date text field somehow editable with a keyboard? I am using the unstable branch under python3 and this does not work at the moment.

**Comment by tYYGH** [comment]
See also #412

**Comment by jflesch** [comment]
Yep, duplicate of #412
