### ISSUE TITLE
[RFE] Set a "title" to a document

### ISSUE THREAD

**Issue by spaetz** [jflesch/paperwork#476]
While date and tags and full-text search are awsome, it would help me to set a "title" or heading to a document, say "gas bill 2015" or "Wedding certificate". This would help me to quickly find the right document when I search all documents with tag "bill", for instance. If this is something that you will not consider, feel free to close this suggestion. Thanks for paperwork in any case!

**Comment by spaetz** [comment]
Looking at the code, I see that the date of a document is used for the "document name". Still, it would be nice to give it a title next to the date. No hurry though.

**Comment by jflesch** [comment]
This is something that has already been requested many times, but I'm actually against it.

Paperwork is designed to let the user being lazy. The less they (have to) do, the better.
Make it possible to add a title and users will feel they have to put one.

In case keywords are missing in a document, it's possible to add additional keywords. But most of the time you don't (shouldn't ?) have to do it.
