### ISSUE TITLE
Catch damaged PDFs

### ISSUE THREAD

**Issue by Jonny007-MKD** [jflesch/paperwork#482]
Hi,

I stumbled upon this by importing a PDF file that was not yet exported by another app.
These are the steps to reproduce:

 1. `head good.pdf > damaged.pdf`
 2. add in paperwork --> stays responsive, but new paper does not show up
 3. restart paperwork --> stuck at indexing new paper

This is the output of the console:

    ERROR  paperwork.frontend.util.jobs   ===> Job DocThumbnailer:0 raised an exception: <class 'GLib.Error'>: poppler-quark: PDF document is damaged (4)
    ERROR  paperwork.frontend.util.jobs    0: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/jobs.py: L  178: _run
    ERROR  paperwork.frontend.util.jobs    1: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/docs.py: L   99: do
    ERROR  paperwork.frontend.util.jobs    2: /usr/local/lib/python2.7/dist-packages/paperwork/backend/common/doc.py: L   92: __get_nb_pages
    ERROR  paperwork.frontend.util.jobs    3: /usr/local/lib/python2.7/dist-packages/paperwork/backend/pdf/doc.py: L  157: _get_nb_pages
    ERROR  paperwork.frontend.util.jobs    4: /usr/local/lib/python2.7/dist-packages/paperwork/backend/pdf/doc.py: L  143: _open_pdf
    ERROR  paperwork.frontend.util.jobs   ---> Job DocThumbnailer:0 was started by:
    ERROR  paperwork.frontend.util.jobs    0: /usr/local/bin/paperwork: L    6: <module>
    ERROR  paperwork.frontend.util.jobs    1: /usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py: L  114: main
    ERROR  paperwork.frontend.util.jobs    2: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/docs.py: L  641: _on_scrollbar_value_changed
    ERROR  paperwork.frontend.util.jobs    3: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/jobs.py: L  247: schedule

I think such an error should be handled more gracefully like

 - deleting the damaged PDF (which could displease the user)
 - ignoring the PDF for now and show a message
 - prompt the user what to do

**Comment by jflesch** [comment]
https://github.com/jflesch/paperwork-backend/commit/c14abf5bd7f880ffc7c902da400de78f897e72e8
https://github.com/jflesch/paperwork-backend/commit/81a5679ae42f0c643291ef5fda097880bfe350e1
e1524529d3f2da90e4c4c7e14e3c527d749eac80
