### ISSUE TITLE
Windows portage

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#488]
I'm considering making a port of Paperwork to Windows. Windows builds would be sold (like [xchat](http://xchat.org/windows/) did, but without the crappy GPL violation).

Just looking how hard it would be.

**Comment by jflesch** [comment]
https://pypi.python.org/pypi/pynsist

**Comment by jflesch** [comment]
Portage has been done.

However, installer will be proprietary (a web installer to respect the GPLv3).

**Comment by lapineige** [comment]
I would have no use of paperwork on Windows. However, if you need to some tests, I can help on w7 and w8.

**Comment by jflesch** [comment]
Noted. But to be honest, I don't think finding testers will be much of a problem (I'll try to enroll my family :).

TODO:
[ ] Mark paperwork.conf as hidden
[ ] "Open directory" doesn't work yet
[ ] Need a diagnostic tool for the scanner for support (can be useful on GNU/Linux too)
[ ] Need a way to get the logs for support (can be useful on GNU/Linux too)

**Comment by lapineige** [comment]
Well no problem, I don't plan to use it on Windows so it's even less work on my side ^^

**Comment by jflesch** [comment]
I forgot something in my TODO list. I intend to try to monetize Paperwork's portage to Windows (we will see if that works ;).

So the TODO is:

- [ ] Mark paperwork.conf as hidden
- [ ] "Open directory" doesn't work yet
- [x] Need a diagnostic tool for the scanners for support (must list all the options and their constraints ; can be useful on GNU/Linux too)
- [x] Need a way to get the logs for support (can be useful on GNU/Linux too)
- [ ] Implements 60 days trial period (Windows only)

**Comment by lapineige** [comment]
> I forgot something in my TODO list. I intend to try to monetize Paperwork's portage to Windows (we will see if that works ;)

I hope it works for you ;)
(I might bought it, even if I don't use it on windows, as a thanks ;)
But you might miss some visibility.

**Comment by jflesch** [comment]
Actually, with one of my friends, we are going to try something weird and alien called "marketing". I find it scary and disgusting, but he assured me it's not (.. well, not that much anyway ..) and can be done cleanly. However, it means investing money from our pocket. So, worst case scenario, we invest a little bit and loose it, and stop investing/marketing ...

**Comment by lapineige** [comment]
Marketing is not always dirty ;)
And it's important even for Open Source project, to have more visibility (honestly, it's not easy to discover Paperwork) and as a result more users, contributors, donators, ... ;)
I think Paperwork deserves to be more known, and a bit of promotion can help :)

**Comment by jflesch** [comment]
- [ ] Mark paperwork.conf as hidden
- [ ] "Open directory" doesn't work yet
- [x] Need a diagnostic tool for the scanners for support (must list all the options and their constraints ; can be useful on GNU/Linux too)
- [x] Need a way to get the logs for support (can be useful on GNU/Linux too)
- [ ] Implements 60 days trial period (Windows only) (see https://openpaper.work/ )
- [ ] Spinner does not work

**Comment by jflesch** [comment]
Done : https://openpaper.work/download

**Comment by jflesch** [comment]
@lapineige 
Actually, I could use your help.
I need people to try Paperwork for WIndows with their own scanner.
It's impossible for me to make sure I support all the possible scanners by myself. So I would appreciate it a lot if you could give it a try, and tell me if it works ? (also if you could tell me which scanner you use exactly, it would be perfect).

Can you get the version 1.0.2 and try it please ?
https://openpaper.work/download

**Comment by lapineige** [comment]
I'm happy to see that you already finish this work :)
(I'm going to advertise it to my friends ^^)

I don't have the scanner with me now, but I can do the test within a week.
I'm going to give you the scanner model, I can test with a "quite" recent printer scanner, and with a pretty basic and old one.

**Comment by jflesch** [comment]
That would be perfect. The more the merrier :-)

**Comment by lapineige** [comment]
I installed it right now, and I've my first error (I installed it on E://, not C://): "Le module spécifié est introuvable".
But it works anyway :)

**Comment by jflesch** [comment]
Hm, ok, weird, but good to know. I'll give it a try in a VM when I can.
Which version of Windows do you use exactly ? and is it 32bits or 64bits ?

**Comment by lapineige** [comment]
62bits Windows 8.
The message begins with E://Programs.
Maybe the change of default path is messing things up ?

**Comment by jflesch** [comment]
Maybe. Did the error happen during installation, or when you started Paperwork ?

**Comment by lapineige** [comment]
On every start, but not during install.

**Comment by jflesch** [comment]
Does the popup you get specified anything more than "Le module spécifié est introuvable" ?

**Comment by jflesch** [comment]
I've tried it on Windows 7 and 10 (in VMs), and I got no popup :/

**Comment by lapineige** [comment]
It's not on C, could it be the issue ?
Is there an log I should check ?

**Comment by jflesch** [comment]
I'm not sure actually.

Maybe:
* either by running it from the shell (cmd)
* or from the diagnostic dialog (Application Menu (the paperplane) --> advanced --> diagnostic)

Maybe there will be some interesting in one of those.

**Comment by jflesch** [comment]
It works fine with Windows 7 64bits + E:\paperwork . I just get a popup everytime I start Paperwork regarding the fact is unsigned (don't ask me why it does pop up on E:\ and not C:\ ....), but no error.

**Comment by jflesch** [comment]
BTW, did you have time to test it with your scanner yet ? which model do you have exactly ?

**Comment by lapineige** [comment]
No I'm sorry, I had some hurry to handle :/
I won't be able to do it until next week. Sorry for the delay.

**Comment by jflesch** [comment]
No problem, don't worry :)

**Comment by lapineige** [comment]
Annoying bug of the day: using "à" key (same as @) on a French keyboard starts Paperwork. (this is really weird ^^).

**Comment by jflesch** [comment]
Already fixed in 1.0.4d .. :)
I just noticed it 2 hours ago.

The problem was when creating the shortcuts for Paperwork (desktop + start menu). Instead of setting the keyboard shortcuts to an empty string, I set them to 0 ... so it binded the key '0'.

**Comment by jflesch** [comment]
Uninstalling / reinstalling 1.0.4d is one way to fix it. I guess you can also simply install 1.0.4d on top of the previous install.

**Comment by lapineige** [comment]
I used 1.0.2, so time to update ^^

**Comment by jflesch** [comment]
@lapineige : If you have a french keyboard, after uninstalling 1.0.2, can you still type "à" ? oO
A member of my family had the problem, and now, she can do "0", "@", but not "à"

**Comment by lapineige** [comment]
I can, without any problem.
