### ISSUE TITLE
Closing and reopening paperwork add a bunch of tags to all documents

### ISSUE THREAD

**Issue by lapineige** [jflesch/paperwork#492]
With only PDF scanned (not tested with real scan) closing Paperwork (0.3.2) and re-opening it add a lot of tags (but not all of them) to all my documents except a few of them (that are tagged with the tag no used on the other documents).

I can provide you some logs if needed.

Thanks :)

**Comment by jflesch** [comment]
Hello,

My guess is that tags were added automatically when the document was scanned (as they should), but weren't immediately displayed for some reason. There was probably a Python exception in background right after the scan + OCR.

Can you run Paperwork from a terminal and do another scan please ? Then please look for a Python stacktrace or any other error in the output (if you don't know what to look for, just post the whole output here).

Thanks in advance,

**Comment by lapineige** [comment]
(thanks for your reactivity :+1: )
> My guess is that tags were added automatically when the document was scanned (as they should)

Oh... so your software is really working as I expected - because I was thinking tags were generated with the OCR, but I didn't find this behavior. That's good news.

So, just to be sure I do everything correctly: if I import a document, it should create tag, or tag it according to the label I created before ?

Right now I just tested with a blank installation, by importing a single pdf. I have only warnings about the time of each OCR
(like that : `WARNING paperwork.frontend.util.jobs   Job OCR:0 took 32772ms and is unstoppable ! (maximum allowed: 500ms)` )


PS: I also encountered this error- but I guess I should open another issue
`INFO   paperwork.frontend.util.actions Action: [Toggle all boxes visibility]
Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/paperwork/frontend/util/actions.py", line 109, in on_switch_activated_cb
   return self.__do()
  File "/usr/lib/python2.7/dist-packages/paperwork/frontend/util/actions.py", line 64, in __do
    return self.do(**kwargs)
  File "/usr/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 1106, in do
    self.__main_win.refresh_boxes()
  File "/usr/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2503, in refresh_boxes
    page.reload_boxes(search)
AttributeError: 'SingleAngleScanWorkflowDrawer' object has no attribute 'reload_boxes'
`

**Comment by jflesch** [comment]
It doesn't create tags. It just apply existing tags (or not) on new documents. It learns from the tags you applied on previous documents. Under the hood, it uses Bayesian filters to guess if it should apply each tag or not.
Usually, it guesses pretty poorly for the ~20 first documents, then it starts to get it right. (hmm, while I'm thinking of it I'm wondering if I should disable tag guessing for the 20 first documents).

> Right now I just tested with a blank installation, by importing a single pdf. I have only warnings about the time of each OCR
> (like that : WARNING paperwork.frontend.util.jobs Job OCR:0 took 32772ms and is unstoppable ! (maximum allowed: 500ms) )

This warning is raised because OCR jobs cannot be interrupted and are quite long, which is a usability problem. It's a known issue that will require a lot of work to fix :/
Anyway, if your problem is really related to tag guessing, I think you will need more than 1 or 2 documents to reproduce (about 5 to 10 I think).

> PS: I also encountered this error- but I guess I should open another issue (done #493 )

Yep, I confirm, this is another issue :)

**Comment by lapineige** [comment]
> It doesn't create tags. It just apply existing tags (or not) on new documents. It learns from the tags you applied on previous documents. Under the hood, it uses Bayesian filters for each tag.
Usually, it guesses pretty poorly for the ~20 first documents, then it starts to get it right. 

Thanks for the explanation. That's definitely something you should put in the wiki page, it was not obvious.
This behavior is very interesting. Thanks for developing paperwork :smiley:

> (hmm, while I'm thinking of it, I'm wondering if I should disable tag guessing for the 20 first documents).

If I had a few tag manually after importing, let's say, 100 documents, and redo the OCR, could it work correctly ?
(because that's almost what I did, but with a few docs), and after almost all the tags went to most of the documents (that were quite close indeed, like a lot of magazine pdf)

> This warning is raised because OCR jobs cannot be interrupted and are quite long, which is a usability problem. It's a known issue that will require a lot of work to fix :/

Don't you think a multi-threaded scan, with 1 thread for 1 page,  could do the job ? (or does it needs the results of the previous pages before ?)
On a classical 4/8 core computer, it could already be a lot faster.

**Comment by jflesch** [comment]
> If I had a few tag manually after importing, let's say, 100 documents, and redo the OCR, could it work correctly ?

From what I understand, your problem is more likely to be a display problem.
I need you to try again in a console, but after adding some documents and tagging first (--> not a blank installation), and see if the problem happens again.

> Don't you think a multi-threaded scan, with 1 thread for 1 page, could do the job ? (or does it needs the results of the previous pages before ?)

Usually, when scanning, you only scan one page at a time, so parallelizing is not that useful.
When importing PDF files, they usually already have their text included, so there is no need for OCR.

I guess it could make sense when importing many PDFs with no text. But I assume this is not a very common case.

**Comment by lapineige** [comment]
Ok, I'll try again if it happens again :)

> I guess it could make sense when importing many PDFs with no text. But I assume this is not a very common case.

Well it's my case, but anyway as you said it's more common to import pdf with text or to scan. Which makes it more complex to do in a multi-thread way.

**Comment by lapineige** [comment]
Ok, I'll try if it happens again :)

> I guess it could make sense when importing many PDFs with no text. But I assume this is not a very common case.

Well it's my case, but anyway as you said it's more common to import pdf with text or to scan. Which makes it more complex to do in a multi-thread way.

**Comment by jflesch** [comment]
ping ? Did it happen again ?

**Comment by lapineige** [comment]
Sorry I had no time to test it. I'll do it ASAP.

**Comment by jflesch** [comment]
Ping ?

**Comment by lapineige** [comment]
Sorry for the delay, I forgot to post my message:

> Usually, it guesses pretty poorly for the ~20 first documents, then it starts to get it right. (hmm, while I'm thinking of it, I'm wondering if I should disable tag guessing for the 20 first documents).

For the test I imported ~ 100 documents, applied a lot of tags (but they are still quite general, most of them could overlap another one) and next imported a few others. Tags were added successfully :)
But in most cases, I got too many tags, and a few irrelevant. I guess I should add more precise tagging.

**Comment by jflesch** [comment]
Ok, if I understand correctly, I can close this ticket ?

**Comment by lapineige** [comment]
Indeed, the issue is solved.

> But in most cases, I got too many tags, and a few irrelevant. I guess I should add more precise tagging.
It's a bit off-topic, but do you know how to improve this ?  Should I add more precise tags ? Try to re-index all the documents ?
