### ISSUE TITLE
Changing "Show all words" during OCR raise and error (but works)

### ISSUE THREAD

**Issue by lapineige** [jflesch/paperwork#493]
When changing the status of the "Show all words" toggle button during an OCR (even while disabeling the option) it raise this error in the console:
http://pastebin.com/wGmXvKCJ
Seems like the attribute is not already defined. (maybe the button should be inactive ?)

**Comment by jflesch** [comment]
Good catch. Should be easy to fix :)

**Comment by lapineige** [comment]
It seems ^^
I'm sorry I had no time to study the code and send a PR. Sounds like a good first bug ^^ (light and inoffensive - if all bugs could be like that... ;) )

**Comment by jflesch** [comment]
No prob, it's already fixed: 95aa47cb1e4c47fd499a9eed0d10eba12bad4616 (will be in Paperwork 0.4).
