### ISSUE TITLE
Setting for export page format

### ISSUE THREAD

**Issue by mrueg** [jflesch/paperwork#494]
When exporting scans to pdf, the page format is set to US Letter by default (which you need to change on every export if you prefer a different one). It would be great if there is a way to set this to a default page format in the settings menu.

**Comment by jflesch** [comment]
Actually, it's using the default value of your system : https://developer.gnome.org/gtk3/stable/GtkPaperSize.html#gtk-paper-size-get-default
I'm assuming it should work for 90% of the users 90% of the time without any extra setting in Paperwork.
Do you have a clear use case when it would really be useful to have another default setting ?

**Comment by mrueg** [comment]
Thanks! Changed LC_PAPER locale, which was set to en_US before, that's the better solution.
