### ISSUE TITLE
Erroneous instructions for Ubuntu

### ISSUE THREAD

**Issue by tiramiseb** [jflesch/paperwork#508]
Hello,

I have tried installing Paperwork 1.0 on Ubuntu 16.04.

The installation was fucked up with the `pip` command, I had to install the `python3-pip` package and use the `pip3` command.

I didn't investigate more, I think you should double-check. Unfortunately, I have no time for that these days.

**Comment by jflesch** [comment]
Darn, I forgot to update the documentation following the switch to python 3 :/

**Comment by jflesch** [comment]
Done : 43c10d2fa748212edc469d9f752752b8d5807b17
Thanks for reporting this omission
