### ISSUE TITLE
Error "scanner_opt_name" is not defined

### ISSUE THREAD

**Issue by textPreferred** [jflesch/paperwork#512]
After successfully detecting my scanner in the settings (cf. screenshot), paperwork complains about a missing (optional?) name (cf. screenshot) and does not scan.

Please find the console log below as well.

Installation was performed via the current "stable" branch: ef467502c471606c991fd5f60b91d946bb4d38f5

![screenshot from 2016-11-09 21 15 16_redacted](https://cloud.githubusercontent.com/assets/1721427/20153380/c5328d38-a6c2-11e6-9d54-703bb586114c.png)
![screenshot from 2016-11-09 21 15 31_cut](https://cloud.githubusercontent.com/assets/1721427/20153385/cbe79f38-a6c2-11e6-861f-4f2a93768986.png)

```
INFO   paperwork.frontend.util.actions Action: [Scan a single page]
INFO   paperwork.frontend.util.config Will scan using plustek:libusb:001:003
INFO   paperwork.frontend.util.config Will scan at a resolution of 300
WARNING paperwork.frontend.mainwindow  Exception while configuring scanner: <class 'NameError'>: name 'scanner_opt_name' is not defined. Assuming scanner is not connected
ERROR  paperwork.frontend.mainwindow  name 'scanner_opt_name' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/paperwork-1.0-py3.4.egg/paperwork/frontend/mainwindow/__init__.py", line 1286, in _do
    (dev, resolution) = get_scanner(self.__config)
  File "/usr/local/lib/python3.4/dist-packages/paperwork-1.0-py3.4.egg/paperwork/frontend/util/config.py", line 343, in get_scanner
    return _get_scanner(config, devid, preferred_sources)
  File "/usr/local/lib/python3.4/dist-packages/paperwork-1.0-py3.4.egg/paperwork/frontend/util/config.py", line 319, in _get_scanner
    pyinsane2.set_scanner_opt(dev, 'source', [config_source])
  File "/usr/local/lib/python3.4/dist-packages/pyinsane2/__init__.py", line 54, in set_scanner_opt
    " Option is not active".format(scanner_opt_name)
NameError: name 'scanner_opt_name' is not defined
INFO   paperwork.frontend.util.dialog Showing popup !
```

**Comment by jflesch** [comment]
Darn. It's a Pyinsane bug. I've pushed a fix ( https://github.com/jflesch/pyinsane/commit/b77c9ae92be2ff6db463579735011d274de9748f ). Can you try it please ?

```
git clone https://github.com/jflesch/pyinsane.git
cd pyinsane
git checkout stable
sudo python3 ./setup.py install
```

**Comment by jflesch** [comment]
Since I'm fairly certain it should fix your problem and that others will have it, I've released a new version with the fix (Pyinsane 2.0.3).
If you installed Paperwork/pyinsane with pip3, the simplest way to update is ```sudo pip3 install -U pyinsane2```.

**Comment by textPreferred** [comment]
Thank you!

I first pulled/installed paperwork:stable, but that did not do the trick.
Then I followed your instructions below (installing your version of
pyinsane) and the scanning started working again.



Hannes

**Comment by jflesch** [comment]
Awesome :)
I'm going to close this ticket. Please comment on this ticket if you still have issues with scanning, and I'll reopen it.
