### ISSUE TITLE
Style problem : The button to access the view settings is slightly bigger than the page numbers

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#514]
Style problem : The button to access the view settings is slightly bigger than the page numbers

**Comment by jflesch** [comment]
![style problem](https://cloud.githubusercontent.com/assets/135331/20172279/bbe82432-a734-11e6-875a-70c4f58ae5ab.png)

**Comment by jflesch** [comment]
The button with the paper plane should also have a border.

**Comment by tiramiseb** [comment]
This button, on my computer running Ubuntu GNOME 16.04, is exactly the same as in your screenshot (and has always been, since the moment it has been created). I thought it was how it should be...

So, if your screenshot shows what you describe as a windows-only problem, I can tell it is NOT a windows-only problem.

**Comment by jflesch** [comment]
[here is what it should be](https://camo.githubusercontent.com/95520dce072d9a544dcd4527fa0e4025f1f03784/68747470733a2f2f7261772e6769746875622e636f6d2f6a666c657363682f7061706572776f726b2d73637265656e73686f74732f6d61737465722f302e332f6d61696e5f77696e646f772e706e67)

**Comment by tiramiseb** [comment]
I don't have what it should be :)

**Comment by jflesch** [comment]
Fixed : cba4900bb61ee97da2852f2f7dca5e7059f5205d
(I think it may make the headerbar slightly bigger in some cases)

**Comment by jflesch** [comment]
Actually, even with the height of the GtkButton/GtkEntry fixed, the default GTK theme in Ubuntu is really ugly (for instance, disabled GtkEntry still have a white background instead of gray) ... but I'm not going to fix the whole GTK CSS just for Ubuntu.
