### ISSUE TITLE
"New document" isn't translated

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#517]
The string "New document" comes from paperwork-backend, not paperwork. So it is currently not translated ....

**Comment by jflesch** [comment]
It will be quite annoying to fix --> postponed to 1.1

**Comment by mjourdan** [comment]
"New paper" would recall the name of the software... Would it not be nice?

**Comment by jflesch** [comment]
Hm, for me, a paper = one page. I'm unsure whether it's only for me or not.

**Comment by tiramiseb** [comment]
one page = a sheet.
a paper = a document.
but I would prefer "document", which is more clear than "paper"...

**Comment by jflesch** [comment]
e69059b14fc838e0fe1482ccb276738893773b5c
(+ a723651e802cc346c36172b749633021f19d9d4b for the French translation)
