### ISSUE TITLE
Missing paperwork icon on toolbar and about dialog

### ISSUE THREAD

**Issue by tiramiseb** [jflesch/paperwork#521]
The paperwork icon isn't displayed on the app menu and in the about window.
Kubuntu 16.10, Paperwork 1.0.1.
![](https://cloud.githubusercontent.com/assets/1292007/20249246/a37612ba-a9f5-11e6-984e-c6cea2ce26c7.png)

May be related to #319.

**Comment by jflesch** [comment]
I've added extra icons in Paperwork 1.0.2 that may fix this issue. Can you give it a try please ?

**Comment by jflesch** [comment]
Reproduced on Debian stable with KDE.

**Comment by jflesch** [comment]
Fix: 9e680cced4d5b4fe93fc6aaac1bed0e1bca50114
Please comment again if it doesn't solve the problem for you, and I will reopen this ticket.

**Comment by jflesch** [comment]
Btw, thank you for taking the time to report this issue.
(I wouldn't have seen it by myself, because Pip don't clean data files correctly .. so my Paperwork was still finding an icon)
