### ISSUE TITLE
After new scan, document list disappears  

### ISSUE THREAD

**Issue by metionina** [jflesch/paperwork#522]
Every time I scan a new document, after the scan is done, the document list on the left disappears. To have it display properly again I need to maximise the window (if it is small) or minimise it (if it is large).    
Not a very big issue, but very reproducible.
Gentoo, Paperwok 1.0.1

**Comment by jflesch** [comment]
I have a feeling you can also try clicking on some button of the interface (for instance one of the button in the header bar).
If it works, it's probably the same bug I see from time to time on Debian sid. Really annoying, and from what I know, it looks like some weird bug in the Gtk event loop :/

**Comment by jflesch** [comment]
Could you just confirm me that clicking on any button (header bar for instance) also unlock the interface please ?

**Comment by metionina** [comment]
I have tried to click all other buttons from the header bar and the document list is NOT restored. The only thing that I found effective so far is resizing the window. 
Please note this is only happening when I add a new document, I don't have problem when I add pages to an existing document.

**Comment by jflesch** [comment]
Hm, so it is not exactly the same bug :/

**Comment by jflesch** [comment]
Actually, this kind of rendering bug will be pretty to fix I think --> I'm going to post pone them to 1.1.0 for now

**Comment by jflesch** [comment]
dc283169d8fa6f0020744c393003c8dce06aff59 fix a very similar issue (document list not appearing when Paperwork starts). I'm going to close this issue for now and release 1.1.1 with this fix. If it doesn't fix this issue, please comment again on this ticket and I will reopen it.
