### ISSUE TITLE
Label editing

### ISSUE THREAD

**Issue by metionina** [jflesch/paperwork#526]
After creating a label it is impossible to edit it. 
If I click on the label colour from the label list, a window appears (the same window than when you create a new label) and even if I edit the label name or the colour after pressing OK all goes back to the original name/colour. 
I couldn't find a way to delete the wrong label. 
Gentoo, paperwork 1.0.1

**Comment by jflesch** [comment]
Weird.

Could run Paperwork from a terminal, reproduce this issue, and see if there is any error or exception that pops up in the terminal please ?

**Comment by metionina** [comment]
Here you are:

`NFO   paperwork.frontend.util.actions Action: [Editing label]
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/labeleditor/labeleditor.glade
INFO   paperwork.frontend.labeleditor Label validated
INFO   paperwork.frontend.labeleditor Label after editing: Color: #000000 ; Text: The Swallows
INFO   paperwork.frontend.mainwindow.docs Label edited. Applying changes
INFO   paperwork_backend.common.doc   20161113_2159_04 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_1921_26 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2005_40 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2005_40 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2005_40
INFO   paperwork_backend.common.doc   20161114_2031_14 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2031_14 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2031_14
INFO   paperwork_backend.common.doc   20161114_1953_30 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_1953_30 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_1953_30
INFO   paperwork_backend.common.doc   20161114_2019_56 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2019_56 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2019_56
INFO   paperwork_backend.common.doc   20161113_2236_30 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2029_51 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2029_51 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2029_51
INFO   paperwork_backend.common.doc   20161113_2234_03 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161113_2230_34 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2019_08 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2019_08 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2019_08
INFO   paperwork_backend.common.doc   20161114_2037_57 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2037_57 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2037_57
INFO   paperwork_backend.common.doc   20161114_2021_20 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2021_20 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2021_20
INFO   paperwork_backend.common.doc   20161113_2218_59 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161113_2254_51 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_1906_44 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_1907_30 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2028_29 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2028_29 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2028_29
INFO   paperwork_backend.common.doc   20161113_2206_21 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2017_46 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2017_46 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2017_46
INFO   paperwork_backend.common.doc   20161113_2204_41 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2034_40 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2034_40 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2034_40
INFO   paperwork_backend.common.doc   20161114_2033_53 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2033_53 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2033_53
INFO   paperwork_backend.common.doc   20161114_1951_14 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161113_2232_17 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2014_04 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2014_04 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2014_04
INFO   paperwork_backend.common.doc   20161114_1923_34 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161113_2208_21 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2008_50 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2008_50 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2008_50
INFO   paperwork_backend.common.doc   20161114_1917_03 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_1917_03 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_1917_03
INFO   paperwork_backend.common.doc   20161114_1908_47 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2016_31 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2016_31 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2016_31
INFO   paperwork_backend.common.doc   20161113_2216_33 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_1926_40 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2024_16 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2024_16 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2024_16
INFO   paperwork_backend.common.doc   20161113_2251_03 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161113_2227_26 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161113_2257_03 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161113_2201_09 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_1922_39 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2002_53 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2002_53 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2002_53
INFO   paperwork_backend.common.doc   20161113_2243_33 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2009_57 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2009_57 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2009_57
INFO   paperwork_backend.common.doc   20161114_1918_42 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_1928_08 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161113_2215_57 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2026_46 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2026_46 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2026_46
INFO   paperwork_backend.common.doc   20161114_2011_17 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_2011_17 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_2011_17
INFO   paperwork_backend.common.doc   20161113_2222_17 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_1920_26 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_1920_26 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Updating modified doc: 20161114_1920_26
INFO   paperwork_backend.common.doc   20161113_2228_02 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.common.doc   20161114_1911_08 : Updating label ([The Swallows] -> [The Swallows])
INFO   paperwork_backend.docsearch    Index: Commiting changes
WARNING paperwork.frontend.util.jobs   Job LabelUpdater:0 took 1324ms and is unstoppable ! (maximum allowed: 500ms)
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.mainwindow  Searching: []
INFO   paperwork.frontend.mainwindow  Got 52 documents
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.mainwindow  Got 0 suggestions
`

**Comment by metionina** [comment]
More readable here
http://pastebin.com/U4KZVqE0

**Comment by jflesch** [comment]
Ok, I think I see the bug.
When you switch back to the document list, the label color has been updated correctly, right ?

**Comment by metionina** [comment]
Yes you are right when I go back to the document list the label is updated even if I don't see it in the label list. This is for the colour.
With the name editing is a bit weird. It seems like the problem is only when I try to edit from lower to upper case or viceversa (?)

**Comment by jflesch** [comment]
Fixed: c033f1d8306dfb0079feb47e360828e4b7e7318e
Will be in 1.0.3.
If you want to test it, you can clone Paperwork's repository (beware the default branch is 'unstable' ; the fix is in the branch 'stable').
I'm going to close this ticket, if you still have problems even with this fix, please comment on this ticket and I'll reopen it.
