### ISSUE TITLE
"resolution" option misnamed on Lexmark MFP (CX510de)

### ISSUE THREAD

**Issue by tiramiseb** [jflesch/paperwork#533]
With my new multifunction printer (Lexmark CX510de), scanner calibration doesn't work, the following error is displayed:

> Erreur lors du scan: Error while scanning: 'resolution'

Traceback in the terminal is:

```
ERROR  paperwork.frontend.util.jobs   ===> Job CalibrationScan:0 raised an exception: <class 'KeyError'>: 'resolution'
ERROR  paperwork.frontend.util.jobs    0: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/jobs.py: L  180: _run
ERROR  paperwork.frontend.util.jobs    1: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/settingswindow/__init__.py: L  361: do
ERROR  paperwork.frontend.util.jobs    2: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/settingswindow/__init__.py: L  398: _do
ERROR  paperwork.frontend.util.jobs    3: /usr/local/lib/python3.5/dist-packages/pyinsane2/__init__.py: L   51: set_scanner_opt
ERROR  paperwork.frontend.util.jobs   ---> Job CalibrationScan:0 was started by:
ERROR  paperwork.frontend.util.jobs    0: /usr/local/bin/paperwork: L    6: <module>
ERROR  paperwork.frontend.util.jobs    1: /usr/local/lib/python3.5/dist-packages/paperwork/paperwork.py: L  153: main
ERROR  paperwork.frontend.util.jobs    2: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/actions.py: L   67: on_button_clicked_cb
ERROR  paperwork.frontend.util.jobs    3: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/actions.py: L   64: __do
ERROR  paperwork.frontend.util.jobs    4: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/settingswindow/__init__.py: L  640: do
ERROR  paperwork.frontend.util.jobs    5: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/jobs.py: L  249: schedule
```

**Comment by tiramiseb** [comment]
This errors occurs when using the printer over the network AND with usb.

**Comment by jflesch** [comment]
.. it seems your scanner doesn't provide the option 'resolution' .. which is kind of a problem ...

Let's check. Can you turn your scanner on, start Paperwork, and then open the diagnostic window please ? (this window is in the application menu --> "advanced"). It's going to collect various informations: logs, various statistics, sys info, and scanner infos (the last one being what I'm looking for).
Then can you send me the output of this dialog (either on this ticket or by email), please ?

**Comment by tiramiseb** [comment]
Ouch. In french it is "diagnostic", not "diagnostique" !

(it is running right now, I will provide data here in a few minutes)

**Comment by tiramiseb** [comment]
Here is the diag result...
[diag_paperwork.txt](https://github.com/jflesch/paperwork/files/611327/diag_paperwork.txt)

**Comment by tiramiseb** [comment]
There seems to be a `scan-resolution` option...

**Comment by tiramiseb** [comment]
I have changed line 398 of paperwork/frontend/settingswindow/__init__.py to:

```
            pyinsane2.set_scanner_opt(dev, 'scan-resolution', [resolution])
```

... and it works as expected.

Maybe you could loop on multiple options, "resolution" and "scan-resolution"...

**Comment by jflesch** [comment]
>  In french it is "diagnostic", not "diagnostique" !

Ah oui mince, c'est subtile... :/ ( http://www.wordreference.com/enfr/diagnostic )

**Comment by jflesch** [comment]
72f3b8b88bd4ce0d9d196bebadfc575810701517 (pour "diagnostic")

**Comment by jflesch** [comment]
"scan-resolution" ...... great, someone wrote a full driver without [reading the documentation first](http://www.sane-project.org/html/doc014.html) ...
I'm going to add a workaround in Pyinsane later today.

**Comment by tiramiseb** [comment]
Maybe devs at Lexmark don't have enough time to RTFM :D

**Comment by tiramiseb** [comment]
(by the way, have you seen the "source" option for the network scanner ? It's f***ing awesome!

**Comment by jflesch** [comment]
Basically, I'm now trying to put the workarounds for the scanners as much as possible in Pyinsane.
So here, what's I'm going to do in Pyinsane:
If there is an option 'scan-resolution', I'm going to add a fake option 'resolution' actually pointing to and reading from 'scan-resolution'

**Comment by jflesch** [comment]
Hm, not sure I'm supposed to see with the option 'source' ? It's what it should be (I have pretty much the same thing on my HP scanner, just I got "ADF" instead of "Automatic Document Feeder")

**Comment by tiramiseb** [comment]
Okay for what you'll be doing for scan-resolution in Pyinsane.

Regarding the "source" option, it's what it should be in the USB scanner (first occurrence) but not in the network scanner (second occurrence).

(both are detailed in the diag file)

**Comment by tiramiseb** [comment]
(regarding the source option, this discussion must continue in #534)

**Comment by tiramiseb** [comment]
Probably related...

As said before, I have changed `pyinsane2.set_scanner_opt(dev, 'resolution', [resolution])` to `pyinsane2.set_scanner_opt(dev, 'scan-resolution', [resolution])` for both occurrences I have seen this function call.

* when calibrating, it displays the "real" scanner zone and I can correctly select the part I want
* at the moment the scan is running, the zone is correcly displayed too
* after scanning, when doing the OCR, it looks like the scan resolution is always 200dpi and the zone taken into account depends on the wanted resolution. If I want 75dpi, it works on an area smaller than the page itself. If I want 300dpi, it works on an area much larger than the page itself.

See attached screencasts: [paperwork_resolution_problem_videos.zip](https://github.com/jflesch/paperwork/files/611837/paperwork_resolution_problem_videos.zip)

@jflesch, if it does not seem related to you, I'll create a new issue...

**Comment by jflesch** [comment]
I'm going to check on mine. I hope it isn't a bug I introduced in 1.0.5 while trying to make some crappy Windows scanners work :/

**Comment by jflesch** [comment]
Does it it only happen on multi-scan, or single scans too ?

**Comment by tiramiseb** [comment]
It happens constantly. Single scan, multi scan, USB, network...

**Comment by jflesch** [comment]
Ok, first I'm going to do a clean patch in Pyinsane, and then we will see if you still have the issue

**Comment by tiramiseb** [comment]
That's perfect

**Comment by tiramiseb** [comment]
```
ERROR  paperwork.frontend.util.jobs   ===> Job ResolutionFinder:2 raised an exception: <class 'RecursionError'>: maximum recursion depth exceeded
ERROR  paperwork.frontend.util.jobs    0: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/jobs.py: L  180: _run
ERROR  paperwork.frontend.util.jobs    1: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/settingswindow/__init__.py: L  256: do
ERROR  paperwork.frontend.util.jobs    2: /usr/local/lib/python3.5/dist-packages/pyinsane2-2.0.7-py3.5.egg/pyinsane2/sane/abstract_proc.py: L  249: _get_options
ERROR  paperwork.frontend.util.jobs    3: /usr/local/lib/python3.5/dist-packages/pyinsane2-2.0.7-py3.5.egg/pyinsane2/sane/abstract_proc.py: L   71: remote_do
ERROR  paperwork.frontend.util.jobs    4: /usr/local/lib/python3.5/dist-packages/pyinsane2-2.0.7-py3.5.egg/pyinsane2/util.py: L   26: __getattr__
ERROR  paperwork.frontend.util.jobs    5: /usr/local/lib/python3.5/dist-packages/pyinsane2-2.0.7-py3.5.egg/pyinsane2/util.py: L   26: __getattr__
```

**Comment by jflesch** [comment]
Hm, ok, should be fixed (still in the same branch)

**Comment by tiramiseb** [comment]
Weird error...
keyerror on `_options`, which is defined in the `__init__`... :/

```INFO   paperwork.frontend.settingswindow Looking for sources of device [lexmark_nscan:libusb/003/005]
ERROR  paperwork.frontend.util.jobs   ===> Job SourceFinder:4 raised an exception: <class 'KeyError'>: '_options'
ERROR  paperwork.frontend.util.jobs    0: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/jobs.py: L  180: _run
ERROR  paperwork.frontend.util.jobs    1: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/settingswindow/__init__.py: L  166: do
ERROR  paperwork.frontend.util.jobs    2: /usr/local/lib/python3.5/dist-packages/pyinsane2-2.0.7-py3.5.egg/pyinsane2/sane/abstract_proc.py: L  249: _get_options
ERROR  paperwork.frontend.util.jobs    3: /usr/local/lib/python3.5/dist-packages/pyinsane2-2.0.7-py3.5.egg/pyinsane2/sane/abstract_proc.py: L   71: remote_do
ERROR  paperwork.frontend.util.jobs    4: /usr/local/lib/python3.5/dist-packages/pyinsane2-2.0.7-py3.5.egg/pyinsane2/util.py: L   30: __getattr__
ERROR  paperwork.frontend.util.jobs   ---> Job SourceFinder:4 was started by:
ERROR  paperwork.frontend.util.jobs    0: /usr/local/bin/paperwork: L    6: <module>
ERROR  paperwork.frontend.util.jobs    1: /usr/local/lib/python3.5/dist-packages/paperwork/paperwork.py: L  153: main
ERROR  paperwork.frontend.util.jobs    2: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/actions.py: L   85: on_combobox_changed_cb
ERROR  paperwork.frontend.util.jobs    3: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/actions.py: L   64: __do
ERROR  paperwork.frontend.util.jobs    4: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/settingswindow/__init__.py: L  514: do
ERROR  paperwork.frontend.util.jobs    5: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/jobs.py: L  249: schedule
INFO   paperwork.frontend.settingswindow Looking for resolution of device [lexmark_nscan:libusb/003/005]
ERROR  paperwork.frontend.util.jobs   ===> Job ResolutionFinder:4 raised an exception: <class 'KeyError'>: '_options'
ERROR  paperwork.frontend.util.jobs    0: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/jobs.py: L  180: _run
ERROR  paperwork.frontend.util.jobs    1: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/settingswindow/__init__.py: L  256: do
ERROR  paperwork.frontend.util.jobs    2: /usr/local/lib/python3.5/dist-packages/pyinsane2-2.0.7-py3.5.egg/pyinsane2/sane/abstract_proc.py: L  249: _get_options
ERROR  paperwork.frontend.util.jobs    3: /usr/local/lib/python3.5/dist-packages/pyinsane2-2.0.7-py3.5.egg/pyinsane2/sane/abstract_proc.py: L   71: remote_do
ERROR  paperwork.frontend.util.jobs    4: /usr/local/lib/python3.5/dist-packages/pyinsane2-2.0.7-py3.5.egg/pyinsane2/util.py: L   30: __getattr__
INFO   paperwork.frontend.settingswindow Selected source: -1
ERROR  paperwork.frontend.util.jobs   ---> Job ResolutionFinder:4 was started by:
ERROR  paperwork.frontend.util.jobs    0: /usr/local/bin/paperwork: L    6: <module>
ERROR  paperwork.frontend.util.jobs    1: /usr/local/lib/python3.5/dist-packages/paperwork/paperwork.py: L  153: main
ERROR  paperwork.frontend.util.jobs    2: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/actions.py: L   85: on_combobox_changed_cb
INFO   paperwork.frontend.settingswindow Scanner sources: []
ERROR  paperwork.frontend.util.jobs    3: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/actions.py: L   64: __do
ERROR  paperwork.frontend.util.jobs    4: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/settingswindow/__init__.py: L  518: do
ERROR  paperwork.frontend.util.jobs    5: /usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/jobs.py: L  249: schedule
```

**Comment by jflesch** [comment]
Yep, weird. It seems for some reason __getattr__ was called before __init__() was even called.
Honestly, this is about the limit of my knowledge in Python, so I've just added an ```if``` to work around that.

Anyway, this time, I took more time to test it (I patched Pyinsane a little to test it on my hardware), and I'm confident it will work this time. I'm merge it on the branch 'stable'. Feel free to give it a try.

I'm closing this ticket. Please comment if I missed anything and I'll reopen it.

**Comment by tiramiseb** [comment]
Seems okay, thanks
