### ISSUE TITLE
Changing source between scan jobs

### ISSUE THREAD

**Issue by tiramiseb** [jflesch/paperwork#536]
Now that I have a super fancy MFP, I will use the feeder to scan documents. However, I sometimes have stuff to scan that can't go into the feeder.

If I want to switch from feeder to flatbed, I am forced to go into the settings window, which is painful for only one document...

**Comment by jflesch** [comment]
Actually you shouldn't have to switch. (my bad, it's undocumented)
Just select the flatbed in the settings. When using the multiple scans dialog, it will automatically switch to the feeder.

**Comment by tiramiseb** [comment]
This behaviour is awesome. It MUST be documented/detailed in the settings window.

**Comment by tiramiseb** [comment]
By the way, doesn't this behaviour make this option useless ?

**Comment by jflesch** [comment]
I guess I should at least replace "source" by "default source"

**Comment by tiramiseb** [comment]
Is there any situation where the default source must not be flatbed ?

**Comment by jflesch** [comment]
I'm actually unsure whether it's useful or not.
I mean, I don't know all the possible hardware in the world, and I guess some may have some weird source lists. The problem is that the source names are not standardized. So while it works fine with ['Flatbed', 'ADF'], it won't with some crappy list like ['Super awesome flatbed', 'Super awesome feeder']

**Comment by tiramiseb** [comment]
I don't know all the possible hardware in the world too, but I guess the vast majority have only one source (mainly flatbed, maybe feeder for portable scanners), other ones have two sources (flatbed and feeder), and that none of them have 3 sources.

**Comment by jflesch** [comment]
Yeah, or they may have ['Single Page', 'Multiple Pages'] ... ;)
BTW, can you confirm me that you actually have the same behavior with 'Single Page' and 'Flatbed', and 'Multiple Pages' and 'ADF' ?

In other words:
- "Flatbed" + button "scan" = 1 page scanned from the flatbed
- "Flatbed" + multi-scan dialog  = many pages scanned from the feeder
- "Single Page" + button "scan" = 1 page scanned from the flatbed
- "Single Page" + multi-scan dialog = .. hm ok, this one shouldn't work yet ..
- "ADF" + button "scan" = 1 page scanned from the feeder
- "ADF" + multi-scan dialog = many pages scanned from the feeder
- "Multiple Pages" + button "scan" = 1 page scanned from the feeder
- "Multiple Pages" + multi-scan dialog = many pages scanned from the feeder
?

**Comment by tiramiseb** [comment]
Nope, the behavious is totally not the same. Details in #534.

**Comment by jflesch** [comment]
a633349c37b366d5c27f028a81562c0c8410e82f : in the settngs, "source" --> "default source"

**Comment by jflesch** [comment]
I think I still need to document that :)

**Comment by jflesch** [comment]
Done: https://openpaper.work/en-us/helpdesk/kb/6/
