### ISSUE TITLE
Import : Make the supported file types clear

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#539]
PNG, JPEG, PDF, etc.

(since we support everything Pillow supports, the list will be long ...)

Proof this would be useful:

https://github.com/jflesch/paperwork/issues/537#issuecomment-262798191
http://www.softpedia.com/get/Office-tools/Other-Office-Tools/Paperwork-Saver.shtml

**Comment by tiramiseb** [comment]
When I import a folder containing many PDFs, does it create multiple documents, or one document with all PDFs "merged" ?

When I import a folder containing many PNGs, does it create multiple documents, or one document with all PNGs "merged" ?

Documentation is really needed !

**Comment by jflesch** [comment]
Regarding the documentation, I've started to work on it here : https://openpaper.work/helpdesk/kb/

**Comment by jflesch** [comment]
We should also try make it clear that it's possible to import folders of PDF.

My current idea:

* Instead of just having an option "import", turn it into a submenu, with the following options inside:
  * "PDF"
  * "Image"
  * "Folder" (while being aware of #94)
* File selection dialog must specify explicitely the file types expected (png, jpg, pdf, folder, etc)

but I also think we need to clarify first #527.

**Comment by jflesch** [comment]
Regarding the doc, mjourdan came up with an idea I like very much : an initial document explaining how to user Paperwork :  #563

**Comment by jflesch** [comment]
https://github.com/jflesch/paperwork-backend/commit/221e3a7928f49d7bf463a9501ff29b8112ac4396
b5bad5f9cde3833e7ddc51e7ecf90ecadc07b3bf
![pouet](https://cloud.githubusercontent.com/assets/135331/23333693/2e106bd2-fb90-11e6-95cf-5247fd04e143.png)

I won't make a submenu. It would make importing files slightly slower and I don't think it would really be useful
