### ISSUE TITLE
[pw1.0.5] Paperwork gets lost when switching documents

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#541]
I’m not sure what triggers the problem, but almost each day, I have Paperwork enter (at least visually) a kind of multiple-document selection where several each click on a document adds this document to the “selection”. Besides, although the page-miniatures are always the right ones, when I click on one such miniature, the single page that gets displayed is from the 1st document of the “selection”, not the page corresponding to the miniature that got clicked.

If it’s any help, clicking on the [+] button (new document) restores a sane behaviour.

**Comment by jflesch** [comment]
Probably related to the key "Control".
Maybe, for some reason, Paperwork does get the signal "key pressed" for this key, but never the signal "key released".

Two questions:
* What is your window manager ?
* Does your WM shortcuts are based on the key "Ctrl" ?

**Comment by tYYGH** [comment]
My WM is Gnome 3, launched from lxdm, hence X11-based, AFAIK. As for the controls, I have not changed the defaults, except that I use Win+Up/Down to switch desktops, instead of Ctrl+Alt+Up/Down. Apart from that, the only global keyboard shortcut I have configured is within Tilda: Shift+F1 toggles the overlay-terminal.

That said, I do use Ctrl a lot: Ctrl+R, etc. in the terminal, Ctrl+click in FF to open a tab, and so on…

**Comment by jflesch** [comment]
Hm, ok here is what we can do:

Just keep using Paperwork as usual. When the bug occurs, [open the diagnostic dialog](https://openpaper.work/fr/helpdesk/kb/1/) and send me the diagnostic output please (by [email](mailto:jflesch@openpaper.work) or on this ticket).

**Comment by jflesch** [comment]
Hopefully, this change should take care of this problem: 03325b4cfc7afb116e2df94f13dbe3e3e127a7a1

**Comment by tYYGH** [comment]
I’ve just read your commit, and from the code I can see how I could indeed trigger my issue by opening Tilda while the focus is on Paperwork.
Thanks :-)

**Comment by jflesch** [comment]
Hm ok, I'm going to assume it solves your problem then :)
If it is not solved in 1.0.6, just comment on this ticket and I'll reopen it.
