### ISSUE TITLE
PDF are not imported recursively

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#546]
When importing a folder, it seems [it only looks for PDF in the parent folder](https://github.com/jflesch/paperwork/issues/240#issuecomment-264169962).

**Comment by camlafit** [comment]
Hi

Need to be confirmed. I do another tries and maybe is ok. Looks an user bug :) I do some others tests before.

**Comment by camlafit** [comment]
Hi

Looks really a mistake, you can reject this issue.

**Comment by jflesch** [comment]
I'm still going to have a look. I did a test, and I'm not 100% sure it works completely fine.

**Comment by camlafit** [comment]
Hi

In this case , maybe a test can be done with directory without pdf and
subdirectories and another directory with pdf and subdirectories.
I doesn't remenber how I've done first, but in my tries, i've some
directory first level with and without document.

In my case looks ok, I do less 10 imports and I've ~4000 documents
imported, then recursive import in some case was ok :)

**Comment by jflesch** [comment]
Tested. It works :)
