### ISSUE TITLE
error when loading labels

### ISSUE THREAD

**Issue by thperret** [jflesch/paperwork#558]
Hi,

First, sorry if I report this issue in the wrong place, this issue concerns paperwork-backend but the issues are disabled on the paperwork-backend repo.

I imported my paperwork folder into a newly installed paperwork (under Debian Sid) and I'm facing the following issue:
```
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2145, in __on_doc_exam_end
    examiner.docsearch.label_list = examiner.labels
  File "/usr/local/lib/python3.5/dist-packages/paperwork_backend/docsearch.py", line 843, in __set_label_list
    self.label_guesser.load(label.name)
  File "/usr/local/lib/python3.5/dist-packages/paperwork_backend/labels.py", line 257, in load
    mkdir_p(baye_dir)
  File "/usr/local/lib/python3.5/dist-packages/paperwork_backend/util.py", line 199, in mkdir_p
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission non accordée: '/w9ZWqNnYcc6p8okoa9xXMG8ZRk='
ERROR  paperwork.frontend.diag        ===========================
```

After debugging a little, it seems to comes from the [base64 conversion](https://github.com/jflesch/paperwork-backend/blob/unstable/src/paperwork/backend/labels.py#L255) and the [folder definition with `os.path.join`](https://github.com/jflesch/paperwork-backend/blob/unstable/src/paperwork/backend/labels.py#L256). In some cases, the base64 string contains one or more slash `/` and it then creates several sub-folders. In the case of the first character being a slash, `os.path.join` discards everything before the base64 encoded string and it then tries to create a folder from the root directory (which obviously lead to the permission error).

The easy fix is to replace [this line](https://github.com/jflesch/paperwork-backend/blob/unstable/src/paperwork/backend/labels.py#L255) by:
`label_hash = base64.encodebytes(label_hash).decode('utf-8').strip().replace('/', '_')` but it's a bit ugly and may not be supported by every filesystems.

I'm a little confused because I don't experience it on my first installation on my other computer (also Debian Sid).
If you want to check, the label leading to the base64 encoded string above is: `Diplôme`

Thanks,
Thomas

**Comment by jflesch** [comment]
Good catch.

Regarding the bug tracker, I must apologize. This is actually the correct one to report paperwork-backend bugs. I've disabled the bug tracker for paperwork-backend because having two bug trackers made it hard for me to follow issues (and often, people don't know if the bug they are reporting is related to Paperwork's frontend or backend).

**Comment by jflesch** [comment]
I think your fix is fine. I don't know any file system that doesn't allow '_'.

Fixed: https://github.com/jflesch/paperwork-backend/commit/11481264cfe809a5cbf5bdf77d527f0d9a7faa6b

Thank you very much for taking the time to debug and report this issue :)
