### ISSUE TITLE
Display of each page takes 2-3 seconds ?

### ISSUE THREAD

**Issue by cgebbe** [jflesch/paperwork#565]
First of all thank you very much for working on this solution, the direction seems really great and promising.

Today I gave it a quick try: First I imported two pdf documents with 2-3 pages each. When I then opened either of them in paperwork, each page takes 2-3 seconds until being displayed. Meanwhile the loading icon is shown. Similiarly, after having opened them and zooming in or out, it takes 1-2 seconds to display each page again. In other pdf viewers (e.g. Xreader) the documents display nearly instantaneously.

I am not sure if Is this a bug, but such long loading times seem very unpractical for an intensive use of the program.

**Comment by jflesch** [comment]
A lot of optimisation have been done in the version 1.1.0 (not yet released ; currently in the branch 'unstable').
One of them is related to displaying PDF files.

**Comment by jflesch** [comment]
For reference:
https://github.com/jflesch/paperwork-backend/commit/d1ffb535cc332475d732fbcd7640028ea1350d66
ee91afbe75ca2bfe4c2c1ce7cf346f58a466c9b2

I'm closing this ticket. If you still have perfomance issues with PDFs in 1.1.0, please comment again on this ticket, and I will reopen it.
