### ISSUE TITLE
[v1.0.5/linux] Rename label => label gets chosen for every new document

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#569]
I renamed label « SomeCompany » to label « Mutuelle ». All happened well. But…
Now, every time I import a PDF or I scan a new document, the latter gets the label « Mutuelle » in addition to the correct labels for this document.

[paperwork-diagnostic.txt](https://github.com/jflesch/paperwork/files/706309/paperwork-diagnostic.txt)

**Comment by jflesch** [comment]
Note: 1.0.6 has been released a while ago

**Comment by tYYGH** [comment]
@jflesch The Archlinux package maintainer wrote:

> I am going to skip the 1.0.6.1 release because only the paperwork-gui version has been updated but not the paperwork-backend. This would force me to put two different version numbers in the PKGBUILD, and I don't think it is worth the effort for the only improvement to display the correct version number in the about screen :-) [1] I'll wait the next release 1.0.7 to re-synchronize everything.
> 
> [1] https://github.com/jflesch/paperwork/commit/2de2178341d67431ae482f07850313c8566d1166

Well… I will download the newer version, although seeing the commit history I doubt it will change much.

**Comment by jflesch** [comment]
Ok, if I understand the maintainer message correctly, they actually mean you're using 1.0.6. But 1.0.6 had a (stupid) bug : I didn't update the about dialog and the main window, so it still displays 1.0.5.
And they didn't want to update to 1.0.6.1.
Fair enough

**Comment by jflesch** [comment]
https://github.com/jflesch/paperwork-backend/commit/d0950c4bdd7aba074798d4eafe56328f29ab3954

**Comment by jflesch** [comment]
It should fix the issue. It will be included in 1.1.0.
If it doesn't, please comment, and I will reopen this ticket.

**Comment by tYYGH** [comment]
I don’t know if this is still relevant… Anyway: yesterday, I had new papers to scan, and once again “Mutuelle” got added to my first scan (alongside the correct label). On a hunch, I decided to run “Réindexer tous les documents” (French) from Paperwork’s Gnome menu. This made the problem disappear :-)

**Comment by jflesch** [comment]
Yep, that's a good workaround
