### ISSUE TITLE
Add the possibility to set save paperwork folder

### ISSUE THREAD

**Issue by Xarkam** [jflesch/paperwork#574]
Add an option to set save folder pour all scaned documents

In my case, we want to save these documents in other place of $HOME/paper without using a symlink or others manipulations.

**Comment by jflesch** [comment]
[... it's the very first settings in the settings window ...](https://raw.githubusercontent.com/jflesch/paperwork-screenshots/master/0.3/settings.png).

The settings window can be found in the application menu. If you use Unity (Ubuntu) or Gnome, the application menu is at the top-left of your screen. If you use anything else, it's in the main window, in the toolbar, it's the button with the paper plane logo.

**Comment by Xarkam** [comment]
Haaaaaaa, okay. Thank.
I did not see the button because it really lacks contrast

![image](https://cloud.githubusercontent.com/assets/331816/22507317/543595ee-e885-11e6-900a-3a66bc326deb.png)

**Comment by jflesch** [comment]
Yep, I did try to have it on the very left of the toolbar to make it more visible, but GTK+ made it really really difficult :/
I'll give it another try later.

**Comment by jflesch** [comment]
Fixed in 1.2.0 : a06504231402dfd13ec5afcc6ce6c89a3e59bb2d
