### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by nodiscc** [jflesch/paperwork#576]
After installing paperwork as described in #575, running the program throws an error

```
$ paperwork
Traceback (most recent call last):
  File "/home/user/tmp/venv/bin/paperwork", line 3, in <module>
    from paperwork.paperwork import main
  File "/home/user/tmp/venv/lib/python3.5/site-packages/paperwork/paperwork.py", line 25, in <module>
    import gi
  File "/home/user/tmp/venv/lib/python3.5/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by tiramiseb** [comment]
Paperwork needs the Python GObject "gi" module (https://download.gnome.org/sources/pygobject/), however you have installed the "gi" package (https://pypi.python.org/pypi/gi/1.2). These are two very different things.
Maybe the installation instructions must be modified, I don't know. I personally have installed the `python3-gi` Ubuntu package before using pip and it works correctly.

**Comment by jflesch** [comment]
```paperwork-shell chkdeps paperwork-backend``` and ```paperwork-shell chkdeps paperwork``` should take care of this problem

**Comment by nodiscc** [comment]
I have reinstalled paperwork from scratch using the most recent install instructions (https://github.com/jflesch/paperwork/commit/6e8fdb7ad4106879e2c5fe2b43d981244b382a24) and no longer have this problem. Instead I have the problem described at #577
