### ISSUE TITLE
Archlinux aur packaging daesn't work on my computer

### ISSUE THREAD

**Issue by VGib** [jflesch/paperwork#588]
Hello,

this follow this discussion https://aur.archlinux.org/pkgbase/paperwork/ , I create an issue as StreakyCobra told me.

I need to install python2-poppler package in order to launch paperwork on my archlinux.

This is due to a python missing dependency in /usr/lib/python3.6/site-packages/paperwork.py
gi.require_version('Poppler', '0.18')

When I have a look, the only package which has poppler.so is python2-poppler:
PS /home/famille/vincent> pkgfile -s poppler.so                                                                                                                                   
community/python2-poppler

@StreakyCobra, you told me you have a poppler.so file in /usr/lib/python*, can you post a pacman -Qo to know which package contains the python library.

Regards,

VGib

**Comment by jflesch** [comment]
Paperwork uses GObject Introspection. GObject Introspection is a way to generate dynamically all the bindings for all the languages.
Therefore, you *don't* need a package named "python-poppler" or whatever.

For instance, on GNU/Linux Debian and Ubuntu, the package name is gir1.2-poppler-0.18

**Comment by jflesch** [comment]
The last comment also show you do not have dependency on libsane. You should.

**Comment by VGib** [comment]
OK thanks,

I found that python2-poppler has a dependency to poppler-glib , when I only install it, it works.
Can you confirm me that the package is required.
Here are the files installed:
poppler-glib /usr/
poppler-glib /usr/include/
poppler-glib /usr/include/poppler/
poppler-glib /usr/include/poppler/glib/
poppler-glib /usr/include/poppler/glib/poppler-action.h
poppler-glib /usr/include/poppler/glib/poppler-annot.h
poppler-glib /usr/include/poppler/glib/poppler-attachment.h
poppler-glib /usr/include/poppler/glib/poppler-date.h
poppler-glib /usr/include/poppler/glib/poppler-document.h
poppler-glib /usr/include/poppler/glib/poppler-enums.h
poppler-glib /usr/include/poppler/glib/poppler-features.h
poppler-glib /usr/include/poppler/glib/poppler-form-field.h
poppler-glib /usr/include/poppler/glib/poppler-layer.h
poppler-glib /usr/include/poppler/glib/poppler-media.h
poppler-glib /usr/include/poppler/glib/poppler-movie.h
poppler-glib /usr/include/poppler/glib/poppler-page.h
poppler-glib /usr/include/poppler/glib/poppler-structure-element.h
poppler-glib /usr/include/poppler/glib/poppler.h
poppler-glib /usr/lib/
poppler-glib /usr/lib/girepository-1.0/
poppler-glib /usr/lib/girepository-1.0/Poppler-0.18.typelib
poppler-glib /usr/lib/libpoppler-glib.so
poppler-glib /usr/lib/libpoppler-glib.so.8
poppler-glib /usr/lib/libpoppler-glib.so.8.8.0

Thanks a lot

**Comment by StreakyCobra** [comment]
> The last comment also show that pyinsane does not have dependency on libsane on ArchLinux. It should.

The one that I maintain, [`python-pyinsane2`](https://aur.archlinux.org/packages/python-pyinsane2/), has `sane` as dependency.

**Comment by StreakyCobra** [comment]
@VGib This one make more sense :-) I'll add it as dependency.

**Comment by StreakyCobra** [comment]
Fixed on AUR side, this issue can probably be closed if everything works for you @VGib.

**Comment by VGib** [comment]
ok close
