### ISSUE TITLE
Move app menu button to the top left corner

### ISSUE THREAD

**Issue by mjourdan** [jflesch/paperwork#589]
On Windows and desktops other than Gnome-Shell, the app menu button should appear in the top left corner, as it does for other apps. So, it should be moved to the left headerbar.

**Comment by jflesch** [comment]
Yep, that's what I tried to do initially ... and failed.
I'll try again. Some other comments have made it obvious that the current presentation is confusing.

**Comment by jflesch** [comment]
Success \o/
a06504231402dfd13ec5afcc6ce6c89a3e59bb2d
