### ISSUE TITLE
No thumbnail on gui

### ISSUE THREAD

**Issue by fabrice-regnier** [jflesch/paperwork#598]
Hi,

Despite the thumbnails were created in the directory "paper", they doesn't appear in the GUI

See attached file
![no_thumbnail](https://cloud.githubusercontent.com/assets/12799446/23070142/61b94e5c-f52a-11e6-9754-2dc3bdb0716c.png)

regards,

f.

**Comment by jflesch** [comment]
Workaround :
- resize the window until the scrollbar of the document list appears
- move the scrollbar

(yeah I know it is annoying ; this is just a workaround, this bug will be fixed)

**Comment by jflesch** [comment]
271349c86b1eb30a99bb59a6b77c46494090aea4
(also on the branch stable --> if there is a 1.1.3, it will be included)
