### ISSUE TITLE
1.2 build failure on F25/Gnome 3.22

### ISSUE THREAD

**Issue by andycowl** [jflesch/paperwork#603]
Thought I'd have a go at building the bleeding edge from Git on Fedora 25 (Gnome 3.22). I have already successfully built 1.1.1 OK.

$ paperwork-shell chkdeps paperwork
WARNING: Missing dependencies:
  - Gnome symbolic icons (/usr/share/icons/gnome/(...)/go-previous-symbolic.svg (python module: (none) ; fedora package : gnome-icon-theme-symbolic)

$ sudo dnf install gnome-icon-theme-symbolic

$ paperwork-shell chkdeps paperwork_backend
All dependencies have been found.

Then I ran 
$ sudo python3 ./setup.py install and got the error. Full build.log attached.

[build.txt](https://github.com/jflesch/paperwork/files/792899/build.txt)

Processing dependencies for paperwork==1.2
Searching for paperwork-backend>=1.2
Reading https://pypi.python.org/simple/paperwork-backend/
No local packages or working download links found for paperwork-backend>=1.2
error: Could not find suitable distribution for Requirement.parse('paperwork-backend>=1.2')

**Comment by jflesch** [comment]
If you install the unstable branch of [paperwork](https://github.com/jflesch/paperwork), you must first install the unstable branch of [paperwork-backend](https://github.com/jflesch/paperwork-backend).
See https://github.com/jflesch/paperwork/blob/unstable/doc/install.devel.markdown#system-wide-installation

**Comment by andycowl** [comment]
Thanks. That resolved my issue.
